### ISSUE TITLE
Help, I can't run melonDS!

### ISSUE THREAD

**Issue by fancymelonub** [StapleButter/melonDS#100]
So, I just got melonDS 0.4 because it have official Wi-Fi support, for some reason melonDS said it needed DS bios files and I was like "Ok.". I put the files on the melonDS directory and it still said that it needed bios files, I tried drag and dropping the files onto the .exe and it crashed. I tried also to run it as administrator yet it still doesn't work. I heard that melonDS can only run DS (Lite) bios files and not 3DS/DSi ones. Though, I can boot to firmware in DeSmuME. If anyone have a fix for this, please post it in the comments.

**Comment by SilasLaspada** [comment]
Have you made sure that the bios files have the correct extension (.bin)? If they end in anything else (like .rom) melonDS will not find them.

**Comment by fancymelonub** [comment]
oh,the arm9 and 7 bios are .rom wile firmware is .bin
thank you for helping me and ill get the correct files

**Comment by fancymelonub** [comment]
i cant find arm9 and arm7 bioses in .bin

**Comment by fancymelonub** [comment]
if you can provide the DS (Lite) Bios files that would be a thanks

**Comment by fancymelonub** [comment]
it worked! thanks!
