### ISSUE TITLE
[PLEASE] WiFi Code for Drastic

### ISSUE THREAD

**Issue by malek78i** [StapleButter/melonDS#101]
Hi MelonDS-Developer!

Could you do an WiFi-Code for Drastic, too? That would be great!

**Comment by Nadia-h** [comment]
DraStic isn't open-source, so you'd have to ask them to add it.

**Comment by malek78i** [comment]
I know but, they want to implent one. They don't know how to develop it. :/

**Comment by malek78i** [comment]
Maybe you can say me, how you do create it? Thank you!

**Comment by malek78i** [comment]
???

**Comment by StapleButter** [comment]
go ask the DraStic guys
