### ISSUE TITLE
Toy Story 3 (USA) extremely slow cutscene scrolling

### ISSUE THREAD

**Issue by SilasLaspada** [StapleButter/melonDS#102]
In Toy Story 3 there is a cutscene where some pictures scroll up on the top screen one after another. On the DS, this takes about a minute or two. On MelonDS at a good FPS of about 40-50, the first picture alone takes several minutes to scroll up completely. The rest of the game runs fairly smoothly, including the cutscene before this one. The console is spammed with "unknown ARM9 IO read16 04004010 02025ED8".

**Comment by StapleButter** [comment]
The unknown IO seems to be DSi IO, ie doesn't matter.

The rest seems to be a timing issue.

**Comment by StapleButter** [comment]
How can I reach the cutscene?

**Comment by SilasLaspada** [comment]
It's the cutscene that starts playing after you finish the first level.

**Comment by SilasLaspada** [comment]
I can confirm, it's fixed!
