### ISSUE TITLE
melonDS Cannot Map D-Pad on Controllers where it is registered as an "Axis"

### ISSUE THREAD

**Issue by gourdcaptain** [StapleButter/melonDS#11]
When trying out melonDS (v0.1, on Arch Linux 64-bit, using the precompiled binaries on the site), my preferred controller for this kind of system, the iBuffalo USB Classic (a replica SNES controller) cannot have its d-pad mapped as melonDS doesn't detect it. My DualShock 3 does work for this. The difference seems to be the D-Pad on the Dual Shock shows up as buttons to the program, while going by the configuration in other emulators the iBuffalo shows up as "Axis 1 +/-" and "Axis 0 +/-" for the D-Pad.

**Comment by StapleButter** [comment]
melonDS is set to use axes 0/1 as an alternate to dpad buttons, so your dpad should work even without mapping it.
