### ISSUE TITLE
Random Music stuttering in The World Ends With You

### ISSUE THREAD

**Issue by Jordy3D** [StapleButter/melonDS#111]
As shown [here](https://www.youtube.com/watch?v=aM_LtS_nfOA), the background music is stuttering. It worked fine beforehand in a different chat scene and afterwards when leaving, and the sound effects seem to be fine, just the BGM. 
I would not say it is major in the slightest, just something I found.

**Comment by voltagex** [comment]
I'd call it major, but not game breaking.

In game audio: https://youtu.be/NAM_s-1UdrM

FMV audio: https://youtu.be/QBEahVBVkrs

**Comment by flamerheart** [comment]
The reason why I stated it was not major at the time was the fact that it almost completely disappeared prior to leaving the conversation. 

Also, that second link does not seem to work, YouTube says it's unavailable

**Comment by voltagex** [comment]
Fixed.
