### ISSUE TITLE
StopEmu

### ISSUE THREAD

**Issue by fr500** [StapleButter/melonDS#113]
https://github.com/StapleButter/melonDS/blob/a15c39546054d8ee608ec1c12e9e14be43dda783/src/NDS.cpp#L350

Does this make sense here?
I had to declare a dummy Platform::Stopemu before including NDS.cpp now (for libretro)

Just wondering if it's the best course of action and if there's gonna be more calls to Platform code from the core. If so, I guess I can add a platform implementation for libretro in a different file to keep the core clean (it's rather messy atm)

**Comment by StapleButter** [comment]
This is called when the emulated system is shut down via the power management device (which the firmware does). In the standalone version, it tells the UI to return to a "no ROM loaded" state.

**Comment by fr500** [comment]
Ah ok, so I'll hook it up properly somehow, thanks.
