### ISSUE TITLE
For macOS ??

### ISSUE THREAD

**Issue by azoreseuropa** [StapleButter/melonDS#13]
Good job on this new emulator but what about macOS ? Is there source to compile it for macOS ? I would like to test it, thanks.

**Comment by StapleButter** [comment]
It should work under macOS, the only missing part is that you'd have to enter keyboard mappings in the .ini manually.

**Comment by azoreseuropa** [comment]
Where, may I ask ? I would like to test it on my macOS and report to you if need to. :D

**Comment by azoreseuropa** [comment]
Hello ? I am waiting for your reply. ;)

**Comment by CuriousTommy** [comment]
@azoreseuropa [try using this command to compile the software](http://melonds.kuribo64.net/board/thread.php?id=4). Note: I haven't tried compiling this software.

**Comment by azoreseuropa** [comment]
It is for linux.

**Comment by CuriousTommy** [comment]
I know it is possible to install [g++ on mac](http://stackoverflow.com/a/2122428) but I starting to realize that this probably isn't the best way to compile the software on a Mac.

**Comment by azoreseuropa** [comment]
I know how to compile the software on a Mac. I done that for Citra emulator and other. :)

**Comment by azoreseuropa** [comment]
*Wave* ??? :D

**Comment by einstein95** [comment]
See #22 for build instructions. Basically, ```g++ -O3 `wx-config --cppflags --static` -I/usr/include/gtk-2.0 $(find ./src -name "*.cpp") `wx-config --libs --static` -lSDL2 -o melonDS```

**Comment by andlabs** [comment]
If `-I/usr/include/gtk-2.0` is necessary to build even with `wx-config`, you shuould be using `pkg-config` instead: `\`pkg-config --cflags gtk+-2.0\`` (and then with `--libs` instead of `--cflags` during the linking phase).

**Comment by azoreseuropa** [comment]
I am confused!

**Comment by StapleButter** [comment]
I'm going to close this because there's no point having two open issues for basically the same thing.
