### ISSUE TITLE
Mario Slam Basketball - Coins/Items are impossible to see through the court.

### ISSUE THREAD

**Issue by JMC47** [StapleButter/melonDS#15]
![image](https://cloud.githubusercontent.com/assets/6598209/25142566/58d337aa-2435-11e7-92a0-f1e93eb6ffe2.png)

There's a shadow in the middle of the screen where an item is floating, but, you cannot see it because the court is behind it.

**Comment by StapleButter** [comment]
Seems to be Z-buffer issues that are also affecting some other games.

**Comment by StapleButter** [comment]
should be fixed by da31af92029af5f9db3c9fcc226414e3789f2682

**Comment by JMC47** [comment]
Still broken.  Can be seen really easy in the backcourt.

**Comment by StapleButter** [comment]
ok now ad58a68fc979524d17858428ea8f755df3d212a5 seems to fix this shit for good
