### ISSUE TITLE
Madden 06 - Broken Character Models

### ISSUE THREAD

**Issue by JMC47** [StapleButter/melonDS#16]
![image](https://cloud.githubusercontent.com/assets/6598209/25142645/b8f5848a-2435-11e7-91b8-9bb133397609.png)

Medusa has the same problem but only worse in current nightly; you can view that issue on Medusa's tracker if curious.

**Comment by StapleButter** [comment]
your players are a special alien half-breed :P 

anyway that's probably textures getting crapoed, but I'd have to debug it

**Comment by StapleButter** [comment]
anyway I found a report in the medusa tracker but it's not the same game

**Comment by StapleButter** [comment]
so, some investigation shows that lighting is shitting itself

it also does that in NO$GBA btw

culling is also malfunctioning but that's a separate issue

**Comment by StapleButter** [comment]
it was actually unrelated to lighting

anyway, fixed
