### ISSUE TITLE
The Legend of Zelda: Phantom Hourglass - Flickering/Discolored Polygons on character models

### ISSUE THREAD

**Issue by JMC47** [StapleButter/melonDS#17]
Seems to happen a lot on Link's hat, or when seagulls cross over Link.

(I'll try to find a consistent spot later.)

**Comment by StapleButter** [comment]
9e622dcc66481350f240c5495f680613b7c98fa6 may fix it, pls check

**Comment by DarkSwan86** [comment]
Tested with the latest bleeding code (ad58a68): seem fixed also for me.
