### ISSUE TITLE
Homie Rollerz (USA) missing 3d model on character select screen

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#18]
using MelonDS 0.2
On the racer selection screen, the top screen should show the selected racer (3d model)
but there is nothing
![homiez](https://cloud.githubusercontent.com/assets/2696404/25322248/ce8a945a-28e7-11e7-9bdf-e7a20d957482.PNG)

I must also say i am very impress with the emulator at this stage
it is emulating games like 
Army Men - Soldiers of Misfortune (USA)
Winter Sports 2009 - The Next Challenge (Europe) (En,Fr,De,Es,It)
My Puppy Shop (Europe) (En,Fr,De,Es,It,Nl,Sv,Da)
New Touch Party Game (Europe)
which no other emulator can run properly yet
good work

**Comment by StapleButter** [comment]
seems to be related to windows, there's something showing up and animating on the first scanline

also thanks :P

**Comment by benderscruffy** [comment]
if u check here u might get an idea (maybe :P )
https://github.com/TASVideos/desmume/issues/27

**Comment by benderscruffy** [comment]
still present on MelonDS 0.3

**Comment by StapleButter** [comment]
yup, I didn't work on it

**Comment by DarkSwan86** [comment]
Still present on ad58a68
