### ISSUE TITLE
Star Wars - The Clone Wars - Jedi Alliance (USA) (En,Fr,De,Es) flickering models

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#19]
using MelonDS 0.2
at the menu screen press start then the screen goes black and nothing

**Comment by einstein95** [comment]
Fixed as of da31af92029af5f9db3c9fcc226414e3789f2682, but has flickering models.

**Comment by DarkSwan86** [comment]
Seem fixed on ad58a68, can you recheck @einstein95?

**Comment by StapleButter** [comment]
I'm closing this until we hear from him
