### ISSUE TITLE
Opening a ROM path via a shortcut CRASH

### ISSUE THREAD

**Issue by theboy181** [StapleButter/melonDS#199]
I have a shortcut on the root of my DATA DRIVE - "ROMS" - Path = X:\EMULATION\NDS ROMS\

If I try to navigate the Open ROM option in MelonDS I get a crash when clicking on the shortcut.  clicking on the folders EMULATION, then NDS ROMS works fine though.

Good work on the emulator btw!

**Comment by StapleButter** [comment]
appears the file picker is unable to process the shortcut (needs some extra flag?), and instead returns it as a filename, causing melonDS to try loading the shortcut file as a ROM
