### ISSUE TITLE
libretro port

### ISSUE THREAD

**Issue by fr500** [StapleButter/melonDS#2]
Not what you're thinking!
Are you ok with us attempting a libretro core early on?
I have it ~~working~~ already

![screenshot 2017-02-07 22 25 04](https://cloud.githubusercontent.com/assets/1721040/22722407/c388dc40-ed84-11e6-8d82-e22e1d7a6351.png)

It's my first attempt at a core but I figure having it early would be good if it suits your future plans

**Comment by StapleButter** [comment]
Sure, go ahead. Just keep in mind that at this point, basic attributes of
the emulator can change at any time. For example, I will eventually change
the framebuffer format to match the DS's actual color precision.
