### ISSUE TITLE
Monster Trucks DS (Europe) (En,Fr,De) trucks keep on flickering 

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#20]
Using MelonDS 0.2
choose quick race and all the trucks keep on flickering even disappering most of the time

**Comment by StapleButter** [comment]
9e622dcc66481350f240c5495f680613b7c98fa6 may fix it, pls check

**Comment by StapleButter** [comment]
nope

it's weird tho. the issue goes away if I disable z-test

**Comment by StapleButter** [comment]
fixed as of 529039f7666692fd528530fef342a58a3084b347 (basically the game uses a VRAM bank to initialize the Z-buffer and there was a chance that rendering started before the bank was mapped)

there are still issues though. decorative objects don't show up because they get W=0 for some reason.

**Comment by StapleButter** [comment]
aaaand fixed
