### ISSUE TITLE
Allow loading ARM Bios' and firmware from ~/.config or AppData

### ISSUE THREAD

**Issue by hcorion** [StapleButter/melonDS#201]
This would give *nix package managers to ability to install melonDS to `/usr/bin` and have melonDS still work.
While you're working on doing it for *nix, might as well do it for the Windows side as well.

**Comment by CuriousTommy** [comment]
[He did have plans for adding configurable paths](http://melonds.kuribo64.net/board/thread.php?pid=288#288), though I do wonder how he is going to implement it.
