### ISSUE TITLE
icon for MelonDS

### ISSUE THREAD

**Issue by hcorion** [StapleButter/melonDS#202]
MelonDS really should have an icon.

It's rather obvious where inspiration should come from for an icon for this emulator. Melons of course! The question is, what melon? Should it be a magical combination melon? Should it be a whole melon? Half a melon? Slice of a melon?

There's also the problem of this being a DS emulator. Citra has ditched the idea of showing the console it emulates through it's icon, perhaps MelonDS should follow suite?

Of course, the icon should be done in svg.

What about posting this issue to /r/emulation? I know we have some talented graphics designers in there.

**Comment by StapleButter** [comment]
Yeah, go ahead, that's a good idea.

**Comment by tommai78101** [comment]
My first SVG file.

[melonDS_literally.zip](https://github.com/StapleButter/melonDS/files/1423862/melonDS_literally.zip)

**Comment by omgmog** [comment]
Just a quick idea, the buttons/etc being like the seeds in a watermelon.

![ic_launcher_app](https://user-images.githubusercontent.com/50949/32133086-de03f006-bbc8-11e7-874c-8a3f58769149.png)

Can provide SVG if needed :+1:

**Comment by MrTimscampi** [comment]
From some experience with contributing to the Numix icon theme for Linux, a thing to keep in mind is that the various elements of the icon should be aligned to a pixel grid (Configure your document to be, say, 48x48px and align things to the grid).

This ensures that the icon will be sharp at every size.

For smaller icons (16x16, 24x24, window title bar type stuff or older Start menus), another, less-detailed icon is also pretty much mandatory for legibility.

**Comment by Krutonium** [comment]
[Reddit](https://www.reddit.com/r/emulation/comments/797as0/melonds_is_looking_for_an_icon/) is giving it a good go, I've got to say I like arienain's idea.

**Comment by LordZane** [comment]
I think @omgmog's is the best so far, but the letters on the buttons should be removed, the oval buttons at the top should be removed, and the border around the screen could be slightly thicker. Other than that great job!

**Comment by jeep70** [comment]
I've been working on something for a little while, trying to go a little simpler and more modern
![image](https://user-images.githubusercontent.com/10716694/32137418-47b82840-bbed-11e7-8e1e-dc4e9df3c1c9.png)

**Comment by arienain** [comment]
Here is my concept:

![1bitmap256](https://user-images.githubusercontent.com/33186186/32138472-69c70abe-bc01-11e7-8142-da6e85cb7679.png)
![2bitmap64](https://user-images.githubusercontent.com/33186186/32138473-6bc30e44-bc01-11e7-98f5-2495ae2aee84.png)
![3bitmap48](https://user-images.githubusercontent.com/33186186/32138475-6d6a202a-bc01-11e7-8ef2-765100df06fe.png)
![4bitmap32](https://user-images.githubusercontent.com/33186186/32138477-6f00be4e-bc01-11e7-83bf-2b2ea5ec72fd.png)

**Comment by limittox** [comment]
Inspired by arienain's design:

![melonds](https://user-images.githubusercontent.com/26973332/32141967-7d2594a0-bce1-11e7-9c3c-dd9f23645444.png)

**Comment by oxysoft** [comment]
I'm not a fan of yours @arienain because the palette feels a bit boring and it's hard to spot the DS theme within the watermelon. @omgmog's is my favorite so far with @limittox in second.

**Comment by lunix4all** [comment]
I really like arienain's design. It's cool how the seeds are also the face buttons. They've got my vote.

**Comment by AxlRocks** [comment]
My shot at it, inspired by those funky, square watermelons from Japan (and Super Mario Sunshine): 

![Icon Preview](https://i.imgur.com/YCZencx.png)

**Comment by hcorion** [comment]
Alright, I'm going to leave it to you, @StapleButter to decide which icon to use.

**Comment by Krutonium** [comment]
@AxlRocks Apparently GIMP can export Paths as SVG, so that shouldn't be an issue. Not that it is my decision, just spreading information.

**Comment by limittox** [comment]
I didn't realize that designs were meant to be done as SVG. I did mine in Photoshop, so I guess mine doesn't qualify. Good luck for everyone still in.

**Comment by Brian151** [comment]
@limittox 
I don't think that it was mandatory to be SVG?
I recall the OP mentioned SVG, but it curiously doesn't anymore.
Also, that's not the end of the world. Even from SWF, you could get an SVG, more or less
I'm guessing yours is EPS, right?
AI,EPS,SWF all can be converted, not always reliably, but it can be done

Technically, I don't think you're even obligated to provide the source files, although it honestly is a good idea.

@hcorion 
When looking for your mention of SVG suggestion, I noticed the bit on abandoning including consoles in the icons. Honestly, I'm partial to icons that indicate what the program does, or the file contains (in the case of file icons) Anyways, the DS isn't a hard one to do. It seems this didn't really impact every icon submitted somehow hints at the DS and a water melon, but just saying... 

That's a personal preference. 
I know this can be hard, sometimes
for example, this one i made: https://raw.githubusercontent.com/Brian151/CAC-Unit-Editor/master/favicon.ico
Not sure why it's displaying at 16x16 pixels, I know it's an icon group with larger icons... I think...
More clearly visible what it is here:
https://github.com/Brian151/CAC-Unit-Editor/blob/master/img/banner.png

Anyways, just saying.
Also, I am occasionally ok with breaking these rules
I just, icons are there to visually indicate what a program does.
There's already enough similar ones, like what MS and Adobe did with MS Office and the Adobe Creative Suite. While possible to read the title, I prefer seeing the icon that's photo-memorized in my brain as
"this is flash!"
"this is firefox!"
"this is paint dot net!"
etc...

sry if i'm kinda rambly!

@StapleButter 
have fun picking!

**Comment by AxlRocks** [comment]
@PFCKrutonium, Interesting, I've never paid attention to or tried that feature and forgot it even existed. Just never really needed it I guess. Trying it briefly, it would probably making converting that icon fairly easy. Certainly useful to know either way, (if I can remember it, that is) thanks!

**Comment by RavetcoFX** [comment]
@limittox I love your design, really sleek and minimalist

**Comment by bryc** [comment]
I love [this one on reddit](https://www.reddit.com/r/emulation/comments/797as0/melonds_is_looking_for_an_icon/dp00ase/) that didn't get much attention, the author didn't seem to get around to finishing it since it was a pixel icon: 
![image](https://user-images.githubusercontent.com/1408749/32610714-95c386e0-c531-11e7-9708-a8fb7037cb2c.png)


I messed around with some pixel scalers just to see what it'd look like as an actual icon and really liked it: 
![image](https://user-images.githubusercontent.com/1408749/32608934-e9c325b2-c52b-11e7-96c2-25be7436a8a2.png)

Then played with some ideas of my own to make it seem more like a folding DS:

![image](https://user-images.githubusercontent.com/1408749/32610634-5e1a9404-c531-11e7-912b-1fdc7a3bb730.png)

I'm no artist, so its still pretty crude, but I like the bold colors. If anyone with talent wants to clean it up in inkscape or illustrator go ahead, that'd be cool!

**Comment by Brian151** [comment]
Honestly, I have a new favorite!

nice find and adaptation @bryc 

The color palette is perfect, just gotta clean the artwork up
Mixed feelings on the polka dot thing, iirc watermelons have stripes

I can't do this myself, but I can outsource to a friend, so I'll contact him like...now
I'd love to see this icon completed!

The pixel version should definitely work as a low-res version, so that's a plus!

(In some ways, I see using vector art to make icons a bit silly, since they're not intended to scale down so drastically. the lower res ones probably should be done as straight pixel art, IMO)

**Comment by Brian151** [comment]
And, he fixed it

![melonds](https://user-images.githubusercontent.com/10995730/32648197-0973ad42-c5b2-11e7-8b2a-90c423291dc0.png)

[melonDSIcon.zip](https://github.com/StapleButter/melonDS/files/1460515/melonDSIcon.zip)

My friend prefers to go by Rennatnave101 or Tanner
If that's of any use?

**Comment by hyarsan** [comment]
I feel something that is inspired by the Nintendo DS logo with a watermelon instead of the D would be nice.
But then it wouldn't work as an Icon?

**Comment by StapleButter** [comment]
Thank you all for the fancypants icons!

In the end, I like limittox's design. For the program icon, something simple is ideal as it'll have to stay distinguishable at 16x16.

However, higher-res graphics could serve as a filler inside the window until a game is launched. AxlRocks' design is cool with the several colors :)

**Comment by Gamerappa** [comment]
The small version of the current melonDS icon looks like a turned happy (water?) melon.
