### ISSUE TITLE
background flickering in Castlevania Dawn of Sorrow. 

### ISSUE THREAD

**Issue by kurayami6** [StapleButter/melonDS#209]
A minute into Castlevania Dawn of Sorrow, you'll walk past some trees. The trees in the background flicker horribly and are obviously broken. 

![capture](https://user-images.githubusercontent.com/31968468/32899052-fd710bfc-cb3d-11e7-9ed0-66ee6902d13c.PNG)

**Comment by windwakr** [comment]
This isn't a bug, it does that on an actual DS.

**Comment by MoochMcGee** [comment]
If this happens on real hardware, can we please close this issue?
