### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by bentley** [StapleButter/melonDS#217]
On my OpenBSD system, melonDS sometimes crashes with a bus error on exit.

    Program terminated with signal SIGBUS, Bus error.
    #0  0x00001d45800841eb in gtk_widget_queue_draw (widget=0xdfdfdfdfdfdfdfdf)
        at gtkwidget.c:5638
    5638    gtkwidget.c: No such file or directory.
    [Current thread is 1 (process 184089)]
    (gdb) bt
    #0  0x00001d45800841eb in gtk_widget_queue_draw (widget=0xdfdfdfdfdfdfdfdf)
        at gtkwidget.c:5638
    #1  0x00001d43219441b0 in _threadsaferefresh (data=<optimized out>)
        at /usr/ports/pobj/melonds-0.6/melonDS-e4f030149b07228a06c6e05a7f0b0e19399d4427/src/libui_sdl/libui/unix/area.c:608
    #2  0x00001d4583a6adf8 in g_main_dispatch (context=<optimized out>)
        at gmain.c:3148
    #3  g_main_context_dispatch (context=<optimized out>) at gmain.c:3813
    #4  0x00001d4583a6b1e5 in g_main_context_iterate (context=<optimized out>, 
        block=<optimized out>, dispatch=<optimized out>, self=<optimized out>)
        at gmain.c:3886
    #5  0x00001d4583a6b54f in g_main_loop_run (loop=0x1d461c785f80) at gmain.c:4082
    #6  0x00001d457ff1673b in gtk_main () at gtkmain.c:1322
    #7  0x00001d4321904bfe in main (argc=2, argv=0x7f7ffffd9328)
        at /usr/ports/pobj/melonds-0.6/melonDS-e4f030149b07228a06c6e05a7f0b0e19399d4427/src/libui_sdl/main.cpp:1187

OpenBSD fills freed memory with 0xdf, so this looks to be a use‐after‐free.

**Comment by StapleButter** [comment]
let me know if this happens again?
