### ISSUE TITLE
What about macOS?

### ISSUE THREAD

**Issue by azoreseuropa** [StapleButter/melonDS#22]
I will be happy to compile it and share it with your download for macOS user. Where can I download it and compile it ? Thanks.

**Comment by azoreseuropa** [comment]
Hello ?

**Comment by StapleButter** [comment]
there's no need to constantly bump your issue threads. I check this every once in a while.

anyway, melonDS should be buildable under MacOS, but I can't do it as I don't have a Mac.

**Comment by azoreseuropa** [comment]
Sorry. Can you give me compile instruction so I can compile it for you and add it to your library ? I compiled Cen64 (N64 emulator), Higan (BSNES - SNES emulator), and etc thanks to their developers helped me through the compiling processing. Can you ? Please ?

**Comment by StapleButter** [comment]
I can only provide you the following command which I used to build it under Linux:

g++ -O3 `wx-config --cppflags --static` -I/usr/include/gtk-2.0 $(find ./src -name "*.cpp") `wx-config --libs --static` -lSDL2 -o melonDS

aside from that, you're on your own, as I have zero experience with Macs.

**Comment by azoreseuropa** [comment]
There is a trouble for me. What I do for terminal in macOS:

Git Clone https://github.com/StapleButter/melonDS.git

It's downloading

I type next one:

cd melonDS
mkdir build
cd build
cmake ../
make

I got an error:

The source directory "/Users/myname/melonDS" does not appear to contain CMakeLists.txt.

Something is missing.. I think relate to cmake ../ or something. We need someone who have a macOS to have an answer. Will you find one ?

**Comment by StapleButter** [comment]
>Will you find one?

Sorry, but I'm not required to spoonfeed you. Ask around yourself.


As for the rest, melonDS doesn't use CMake. This is something I want to address, though.

**Comment by azoreseuropa** [comment]
I will ask anybody around in your forum there, thanks.

**Comment by StapleButter** [comment]
well, we got Cmake for Linux, maybe it also works for Mac. try it out

I can't give support though, so you'll be on your own

**Comment by azoreseuropa** [comment]
I already mentioned above. cmake ../ doesn't work.

**Comment by StapleButter** [comment]
notice that we added a Cmake build system inbetween

**Comment by azoreseuropa** [comment]
So, I am doing this right ? Here:

git clone https://github.com/StapleButter/melonDS.git

It's downloading and 100% complete

Now, I type next one:

cd melonDS
mkdir build
cd build
cmake ../

If so then why do I got an error before I type 'make'? Sorry to bother you but I am trying to figure it out. :)

**Comment by azoreseuropa** [comment]
*WAVE* ?? :)

**Comment by StapleButter** [comment]
sigh

**Comment by WilliamLCobb** [comment]
@azoreseuropa I'm working on a macOS configuration that uses XCode and should be much simpler to build with when it's done. I'll let you know

**Comment by azoreseuropa** [comment]
William, thank you. Much appreciate. I will keep my eyes here from you. *waiting*. :)

**Comment by azoreseuropa** [comment]
@WilliamLCobb,

have you done it already ? :)

**Comment by StapleButter** [comment]
azoreseuropa: to be entirely honest, I have no problem with helping people, but I refuse to spoonfeed them. You know what they say, give a man a fish and he'll eat for a day, etc...

And what you're doing is pretty much waiting for people to spoonfeed you, and insisting because you don't get an answer. You can look for other places where people would be likely to be able to help you (coding forums, Mac related forums, whatnot, I don't know). You can research your issues (using for example, you know, Google). There are many things you can do that could be more productive than coming here "I have an error" and waiting for people to magically figure it out and hold your hand until it works.

**Comment by azoreseuropa** [comment]
You are absolutely right, StapleButter and I respect you for that. 

Matter of fact, Yes, I have posted at the MelonDS forum, Google it and GBATEMP (I bet you know it, 👍 ) and they are kindly enough to answered me and they don't seem to know how. 

That's why William is my only hope to help me out. I don't have problem with compiling Cen64, Dolphin, higan (it was the hard to compiled and they are nice to help me out step by step and I succeed), and now this. I am trying to write them into instruction notepad so I can help people how to compile those things if they need to. :)

**Comment by StapleButter** [comment]
comments are staying open

anyway, what is the error message you're getting? because you know, just saying "I have an error, please help me" is like going to the doctor and saying "hello doc, something hurts on my body, please heal me".

**Comment by azoreseuropa** [comment]
Thank you.

I gave you the exact error and I am not saying that I have an error, please help me just like hello doc blah blah, lol! 

I know that, smile. Again, I gave the error and the problem is you cannot fig are it out because you don't have a MAC and William has a MAC just like me. 

Read William's comment. He seems to know something so thats what I am trying to find out what he knows. He seems not to answer just yet as he said he would let me know soon.

**Comment by StapleButter** [comment]
"If so then why do I got an error before I type 'make'? Sorry to bother you but I am trying to figure it out. :)"

that's not what I call giving the exact error

**Comment by azoreseuropa** [comment]
Okay.. I redo it now.. Oh. Now I got a new message... Almost work! It's in processing then now I got this new message:

CMake Error at /usr/local/Cellar/cmake/3.8.0/share/cmake/Modules/FindGTK2.cmake:640 (message):
  Could not find GTK2 include directory
Call Stack (most recent call first):
  CMakeLists.txt:31 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/myname/melonDS/build/CMakeFiles/CMakeOutput.log".

**Comment by StapleButter** [comment]
https://github.com/StapleButter/melonDS/blob/master/CMakeLists.txt#L30

I figured that that would limit it to Linux. dunno if GTK2 is needed under MacOS. so, try removing those 4 lines from CMakeLists.txt.

**Comment by azoreseuropa** [comment]
I google it and GTK2 can be used under macOS, should I ?

And

After I removing those 4 lines from CMakeList.txt and just type cmake ../ again ?

**Comment by StapleButter** [comment]
I said 4 lines, not 4 paragraphs. The part from "if (UNIX)" to "endif (UNIX)".

GTK2 shouldn't be required under MacOS. Actually, it shouldn't be required at all -- it's only because we need keycode definitions for the input config dialog.

**Comment by azoreseuropa** [comment]
Alright... after I deleted 

if (UNIX)
find_package(GTK2 2.0 REQUIRED)
include_directories(${GTK2_INCLUDE_DIRS})
endif (UNIX)

and click save and what it looks like:

https://pastebin.com/88ZULShK

Then I type cmake ../ and I got this message:

https://pastebin.com/ChXDTR4b

**Comment by StapleButter** [comment]
so it looks like wxWidgets itself wants GTK2??

well, install the GTK2 dev package, I guess

**Comment by azoreseuropa** [comment]
I think I did it... You have to install GTK+ and wxWidgets too.. I got this:

https://pastebin.com/zt9k0wRE

The problem is that this emulator is not GUI.. I will have to command line it. What is it ? So I can test DS rom to see if this emulator is able to run. IF everything is successfully then I can write an instruction to you so you can add Mac tutorial on your git list along with linux and windows, how is that ? :)

**Comment by azoreseuropa** [comment]
I cannot find the command line for it. Is there ? I want to test it and report to you so I will know that Mac version work or not.

**Comment by StapleButter** [comment]
well, it looks like it built successfully, so... try it out, I guess

**Comment by azoreseuropa** [comment]
Actually here:

Last login: Wed May 10 11:36:59 on ttys000
mynames-MBP:~ myname$ /Users/myname/melonDS/build/melonDS ; exit;
2017-05-10 11:37:09.167 melonDS[25684:142741] -[SDLApplication transformToForegroundApplication]: unrecognized selector sent to instance 0x7fdc75e03480
2017-05-10 11:37:09.168 melonDS[25684:142741] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SDLApplication transformToForegroundApplication]: unrecognized selector sent to instance 0x7fdc75e03480'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff94c4837b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffa9a3c48d objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff94cc9f04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff94bba805 ___forwarding___ + 1061
	4   CoreFoundation                      0x00007fff94bba358 _CF_forwarding_prep_0 + 120
	5   libwx_osx_cocoau_core-3.0.dylib     0x000000010e8465d1 _ZN5wxApp9DoInitGuiEv + 259
	6   libwx_osx_cocoau_core-3.0.dylib     0x000000010e8868fc _ZN5wxApp9OnInitGuiEv + 30
	7   libwx_osx_cocoau_core-3.0.dylib     0x000000010e8fb49f _ZN9wxAppBase10InitializeERiPPw + 135
	8   libwx_osx_cocoau_core-3.0.dylib     0x000000010e885f4b _ZN5wxApp10InitializeERiPPw + 205
	9   libwx_baseu-3.0.dylib               0x000000010ede2896 _Z12wxEntryStartRiPPw + 232
	10  libwx_baseu-3.0.dylib               0x000000010ede34ce _Z12wxInitializeiPPw + 66
	11  libwx_baseu-3.0.dylib               0x000000010ede338e _Z7wxEntryRiPPw + 14
	12  melonDS                             0x000000010dcae4cf main + 111
	13  libdyld.dylib                       0x00007fffaa321235 start + 1
	14  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by azoreseuropa** [comment]
Sorry to bother you but ??? Been a 5 days. I complete with other githubs for other emulators and finished with them. Now I m struggling with yours. Your emulator is my last GitHub to figure out.

**Comment by StapleButter** [comment]
you're on your own, atleast until a Mac-savvy person shows up. as I said, I know zero about Macs. sorry.

**Comment by azoreseuropa** [comment]
Ok.

**Comment by strikersix23** [comment]
You need to instal libc++ binaries for that to work

**Comment by strikersix23** [comment]
Heres the library website
https://libcxxabi.llvm.org/

**Comment by surenzxx** [comment]
Has anyone made a fork with a built version of it for Mac OS?

**Comment by RSDuck** [comment]
you can try melonDS with RetroArch, they finally updated their core to a recent version melonDS not too long ago.

Otherwise there's not much which can be done.
