### ISSUE TITLE
Separate build fails

### ISSUE THREAD

**Issue by bentley** [StapleButter/melonDS#221]
2e82a4f26ac99a1a93afdcb6bbfc4095d0933cc6 broke out‐of‐source builds:

    $ mkdir build
    $ cd build
    $ cmake ..
    -- The C compiler identification is Clang 5.0.0
    -- The CXX compiler identification is Clang 5.0.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1")
    -- Checking for module 'gtk+-3.0'
    --   Found gtk+-3.0, version 3.22.26
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/melonDS/build
    $ make
    [  1%] Generating melon_grc.c
    Failed to open file “melon_grc.xml”: No such file or directory
    *** Error 1 in . (CMakeFiles/melonDS.dir/build.make:62 'melon_grc.c': glib-compile-resources --generate-source melon_grc.xml)
    *** Error 1 in . (CMakeFiles/Makefile2:67 'CMakeFiles/melonDS.dir/all')
    *** Error 1 in /tmp/y/melonDS/build (Makefile:130 'all')

**Comment by retro-wertz** [comment]
confirmed this using ArchLinux

**Comment by lyneca** [comment]
Confirmed here
