### ISSUE TITLE
Audio initialization fails when compiling master branch on windows (codeblocks)

### ISSUE THREAD

**Issue by GermanCoding** [StapleButter/melonDS#226]
Steps to reproduce:

1. I cloned the master branch
2. I added SDL to the dependencies (I tested version 2.0.5 [used by the official 0.6b release] and 2.0.7 [latest available] - same problem on both versions)
3. I compiled the project using Code::Blocks and a MinGW GCC compiler.

Two problems arise:

1. The project does not compile until adding `#include <string.h>`  to `main.cpp`.
2. When executing the compiled executable, there is no sound. In debug configuration the following error message is displayed:

> Audio init failed: WASAPI can't initialize audio client: CoInitialize was not called.

(message was localized - german, translated to english)

Tracing the error, it is triggered during audio init in `main.cpp` function `EmuThreadFunc()`

```
SDL_AudioDeviceID audio = SDL_OpenAudioDevice(NULL, 0, &whatIwant, &whatIget, 0);
if (!audio)
{
        printf("Audio init failed: %s\n", SDL_GetError());
}
```

However, the audio works fine in the precompiled windows release version (0.6b). This error appears only when I compile the project for myself.

I do have a fix available for both issues (see [this](https://github.com/GermanCoding/melonDS/commit/411ed31a0030794154994c8af3abeca1b7575d9c) commit), but I'm not sure why this issue is not present in the beta?

**Comment by StapleButter** [comment]
I'm late as fuck, but

How does it go if you try building revision 2e82a4f26ac99a1a93afdcb6bbfc4095d0933cc6 ?

**Comment by GermanCoding** [comment]
Hi, thanks for the response.

When compiling the current upstream version (aa3fc8be68e0d98649c33f15582e731d35a37041) and discarding my local changes, I've two problems:

- Same as above, the project does not compile until adding `#include <string.h>` to `main.cpp` (the file uses string functions and my compiler complains that they aren't defined unless I add the header. Don't know, maybe my compiler is too strict or so...

- When that's fixed the program compiles but immediatly crashes after startup - see screenshot below
![melonds_crash](https://user-images.githubusercontent.com/4279661/39304664-aed66e9c-495a-11e8-8d33-56661858cd96.png)
I wasn't yet able to figure out what the reason for the crash is, investigating that.

When going back in time to commit 2e82a4f26ac99a1a93afdcb6bbfc4095d0933cc6 as you asked, I've the default problem (add `#include <string.h>` to `main.cpp`), but after that I've **zero issues - the project compiles & runs without further modification from my side with sound**

That means the issues mentioned above are introduced somewhat later in the code.

**Comment by Zapeth** [comment]
I got the same issue when compiling over cmake with MinGW (no sound, same error message), no issue with the mentioned header include though.

This is the most relevant I could find online about this issue: https://trac.ffmpeg.org/ticket/6891

I don't know if manually calling `CoInitializeEx` in the code is the proper way to resolve this issue or something else in the code should be changed, but at least sound is working for me again after doing so.

To be specific, I added this at the start of `EmuThreadFunc()` (somewhere before calling `SDL_OpenAudioDevice()`):
```
#ifdef __MINGW32__
	CoInitializeEx(NULL, COINIT_MULTITHREADED);
#endif
```
And this at the end of `EmuThreadFunc()` (somewhere after `SDL_CloseAudioDevice()`):
```
#ifdef __MINGW32__
	CoUninitialize();
#endif
```
The `CoUninitialize` is really only required for cleanup (and if you want to be even more correct, you should check the return value of `CoInitializeEx`), so not really required if you don't care about proper coding.

**Comment by Zapeth** [comment]
Yeah, audio plays now for me with the latest revision without having to add the changes that I previously mentioned, thanks.
