### ISSUE TITLE
Error compiling using CodeBlocks on Windows 10 x64

### ISSUE THREAD

**Issue by SilasLaspada** [StapleButter/melonDS#228]
Compiling the main branch MelonDS using CodeBlocks fails with the following errors: 
||=== Build: DebugFast Windows in melonDS (compiler: GNU GCC Compiler) ===|
C:\Users\silas\Desktop\GIT\melon\trunk\src\Config.cpp||In function 'FILE* Config::GetConfigFile(const char*, const char*)':|
C:\Users\silas\Desktop\GIT\melon\trunk\src\Config.cpp|118|error: 'PWSTR' was not declared in this scope|
C:\Users\silas\Desktop\GIT\melon\trunk\src\Config.cpp|119|error: 'FOLDERID_RoamingAppData' was not declared in this scope|
C:\Users\silas\Desktop\GIT\melon\trunk\src\Config.cpp|119|error: 'appDataPath' was not declared in this scope|
C:\Users\silas\Desktop\GIT\melon\trunk\src\Config.cpp|119|error: 'SHGetKnownFolderPath' was not declared in this scope|
C:\Users\silas\Desktop\GIT\melon\trunk\src\Config.cpp|123|error: cannot convert 'std::__cxx11::string {aka std::__cxx11::basic_string<char>}' to 'const char*' for argument '1' to 'FILE* fopen(const char*, const char*)'|
C:\Users\silas\Desktop\GIT\melon\trunk\src\Config.cpp||In function 'void Config::Save()':|
C:\Users\silas\Desktop\GIT\melon\trunk\src\Config.cpp|210|warning: format '%s' expects argument of type 'char*', but argument 4 has type 'void*' [-Wformat=]|
C:\Users\silas\Desktop\GIT\melon\trunk\src\Config.cpp|210|warning: format '%s' expects argument of type 'char*', but argument 4 has type 'void*' [-Wformat=]|
||=== Build failed: 5 error(s), 2 warning(s) (0 minute(s), 0 second(s)) ===|

I tried using Release, Debug, and DebugFast, but all of them failed. The jit branch compiles normally.

**Comment by hcorion** [comment]
Shoot, that's my fault, I didn't realize the build was using GNU GCC on windows.

**Comment by SilasLaspada** [comment]
Fixed by newest commit
