### ISSUE TITLE
Orcs & Elves

### ISSUE THREAD

**Issue by windwakr** [StapleButter/melonDS#23]
1. Most objects aren't visible when they should be. They'll appear and disappear as you move around. The game uses box tests to determine whether to show objects, so it may be an issue with your box test code.
2.  The health remaining number is behind the health meter(heart on lower right side of the top screen) when it should be on top
3. Some text renders incorrectly, see: 
![untitled](https://cloud.githubusercontent.com/assets/284886/25361076/397a4c88-291a-11e7-8544-107352d7541a.png)

Tested on melonDS 0.2, compared against real hardware.

**Comment by StapleButter** [comment]
looks like it doesn't like repeated letters for some reason

as for the rest it could also be zbuffer issues

**Comment by windwakr** [comment]
Well, the issue in 1. goes away if I modify boxtest to always return true.

**Comment by StapleButter** [comment]
it's weird, but I'll check the boxtest code

**Comment by StapleButter** [comment]
this should be fixed by the latest commit

**Comment by windwakr** [comment]
Can confirm, no. 1 is fixed by the latest commit. No. 3 seems to have been fixed at some point in the past. 
No. 2 still exists. Here's a comparison between melonDS and DeSmuME(but matches hardware in this case):
https://i.imgur.com/OWLF5h4.png

**Comment by StapleButter** [comment]
2 seems to be due to missing Y-sorting

**Comment by StapleButter** [comment]
fixed
