### ISSUE TITLE
Fighting Fantasy: The Warlock of Firetop Mountain

### ISSUE THREAD

**Issue by windwakr** [StapleButter/melonDS#24]
This game has some issues where parts of the level don't render when looking at them at certain angles. I don't know how to describe it well. For example, load up the game and get into the corner by the stairs then look around. This doesn't happen on real hardware.
![untitled](https://cloud.githubusercontent.com/assets/284886/25361402/ebce0df6-291b-11e7-90d4-ce4c7d939d7a.png)

Tested on melonDS 0.2, compared against real hardware.

**Comment by StapleButter** [comment]
Appears to be Z-buffering issues. Haven't yet figured out what's wrong with that.

**Comment by StapleButter** [comment]
should be fixed by da31af92029af5f9db3c9fcc226414e3789f2682
