### ISSUE TITLE
Error when compiling (sorry, unimplemented: 64-bit mode not compiled in)

### ISSUE THREAD

**Issue by Rempa212** [StapleButter/melonDS#240]
I just downloaded the source code, opened it in codeblocks, and tried to compile the program, but just get this error : sorry, unimplemented: 64-bit mode not compiled in
I'm probably really stupid, but i need help...

**Comment by GermanCoding** [comment]
Looks like your compiler (probably MinGW) is 32 bit and doesn't support compiling 64 bit. You need to use something that is capable of compiling 64bit, e.g [https://mingw-w64.org/](https://mingw-w64.org/) (installer is here: [https://sourceforge.net/projects/mingw-w64/](https://sourceforge.net/projects/mingw-w64/))  - download and install and make sure your Code::Blocks uses the new enviroment.

**Comment by GermanCoding** [comment]
Have you tried cleaning & rebuilding the project after changing the compiler? The compiler settings appear to be good judging from the screenshot.

**Comment by Dyathias** [comment]
Yeah, for some reason it's still giving the same error. I tried reinstalling and cleaning the build but I still can't build it. Is there an updated command line to build it directly in MSYS2?

**Comment by strikersix23** [comment]
You need a 32-bit version of windows use Vbox with a 32 bit version of windows that's nearest to yours. I had the same issue i fixed it with what i just said make sure you have network access to the vm to share the files

**Comment by StapleButter** [comment]
I use msys64, which comes with mingw64

works fine, and I'm on 64-bit Windows. no need for arcane shit like 32bit
VMs.
