### ISSUE TITLE
Russel Grant's Astrology is sideways

### ISSUE THREAD

**Issue by kurayami6** [StapleButter/melonDS#242]
Entire game is sideways, which can be fixed by rotating the screen to 270, but it probably shouldn't be sideways by default, right? 

Windows 7. i5. GTX 970. 

![capture](https://user-images.githubusercontent.com/31968468/39358674-3b18c1a2-4a5a-11e8-987f-320b0bf8268e.PNG)

Akai Ito is also sideways. I'll update If I find more.

![capture](https://user-images.githubusercontent.com/31968468/39406849-90b5ab28-4c00-11e8-99ba-9fd77b1c73b2.PNG)

**Comment by StapleButter** [comment]
as a side note on this: melonDS has no way to detect how the screens should be oriented.
