### ISSUE TITLE
[Feature Request] Remember file browser directory

### ISSUE THREAD

**Issue by Dirbaio** [StapleButter/melonDS#244]
On Linux, the file browser for Open ROM always opens the "Recents" folder. This means if you want to try out a bunch of ROMs in a folder, or reload the ROM, you have to nagivate to the folder over and over, which is somewhat annoying.

Just a small usability improvement :)

**Comment by StapleButter** [comment]
indeed. I had planned something like that, but I need to actually code it.

**Comment by StapleButter** [comment]
done
