### ISSUE TITLE
D-Pad axis0/axis1 in Joystick input config?

### ISSUE THREAD

**Issue by ghost** [StapleButter/melonDS#246]
I have an original Super Famicom controller with the Mayflash USB adapter. This is recognized as a 2-Axis 10-Button pad.
X, A, B, Y, L, R, Select and Start are buttons 1, 2, 3, 4, 7 ,8 ,9 ,10 respectively. D-Pad is 2 Axis.
Despite being recognized as a 10 button pad, nothing actually uses 5 or 6.

Problem is, melonDS only recognizes the joypad buttons, while axis input is ignored. I can bind ABXY/LR/Start/Select to their respective buttons, but I can't bind the D-Pad to the directional buttons.

Am I missing something? I guess JoyToKey can be an option in the meantime (sorta, because melonds does not support keyboard background input like it does joypad), but it would be nice if support could be added at some point.

(I know you've been having life issues and motivation is lacking, so no rush. If there's any info I can provide to help add support for it I'd be happy to do so.)

**Comment by Ammako** [comment]
I guess I should have looked before posting. This is the same issue as #11

>melonDS is set to use axes 0/1 as an alternative to dpad buttons, so your dpad should work even without mapping it.

The person who opened that issue never bothered reporting back, but it does *not* work without mapping.

[image](https://i.imgur.com/n4vLfIQ.gif)

**Comment by StapleButter** [comment]
the issue was addressed, such that you don't need dpad mapping anymore to have an analog axis work
