### ISSUE TITLE
Phineas and Ferb: Across the 2nd Dimension (USA)

### ISSUE THREAD

**Issue by SilasLaspada** [StapleButter/melonDS#25]
In Phineas and Ferb: Across the 2nd Dimension, the main menu has broken text and selecting any option crashes on a black screen.

![nds2d](https://cloud.githubusercontent.com/assets/24215969/25364904/ca1dde50-2922-11e7-868a-25c32d13dbaa.JPG)

**Comment by StapleButter** [comment]
I heard 4 is a very good game mode, though


more seriously tho, I need to look into it, seems to be a serious bug

**Comment by SilasLaspada** [comment]
Ok. The console is also spamming "unknown arm9 read32 ..." nonstop after choosing the first option (main game). The second option (options) spams 
"bad CPU mode A000001F
unknown arm9 read32 ..." nonstop. I hope that helps narrowing down the problem some!

**Comment by StapleButter** [comment]
Are you sure you got the USA ROM though? I tried that one and all I get is a white screen, be it on 0.2 or on latest.

**Comment by SilasLaspada** [comment]
Yes I have the right ROM, dumped it myself. The difference must be the save file. If I get rid of the .sav file, I only get a white screen as well. Do you want me to give you the save so you can troubleshoot further?

**Comment by StapleButter** [comment]
yup, that'd be cool

**Comment by SilasLaspada** [comment]
Here you go! Let me know if you need anything else.
[DSP3_B5VE00.zip](https://github.com/StapleButter/melonDS/files/955169/DSP3_B5VE00.zip)

**Comment by StapleButter** [comment]
Thanks!

Wait though... it's a 512 byte file. Sooooo... that game uses tiny EEPROM, and melonDS detects it wrong. That's atleast one thing.

But when given an existing savefile, it should detect the proper type from the size, so that's out of the way.

**Comment by SilasLaspada** [comment]
I can verify that it now works with a proper savefile! Should I close this issue or leave it open until melonDS can handle everything properly without the savefile?

**Comment by StapleButter** [comment]
I'd leave it open as a reminder that I still need to fix shit :P

**Comment by SilasLaspada** [comment]
Everything appears to work correctly as of the latest commit, including generating a proper savefile.
