### ISSUE TITLE
Can't build on Linux

### ISSUE THREAD

**Issue by blacksparrow123** [StapleButter/melonDS#253]
Hello
I'm trying to install melonds via AUR and getting this error:
[  8%] Building CXX object CMakeFiles/melonDS.dir/src/ARM.cpp.o
/tmp/pamac-build-anton/melonds-git/src/melonds/src/ARM.cpp:164:21: error: variable or field «Savestate» declare as void
 void ARM::Savestate(Savestate* file)
                     ^~~~~~~~~
/tmp/pamac-build-anton/melonds-git/src/melonds/src/ARM.cpp:164:30: error: expected primary-expression before «*» token
 void ARM::Savestate(Savestate* file)
                              ^
/tmp/pamac-build-anton/melonds-git/src/melonds/src/ARM.cpp:164:32: error: no declaration «file» in this scope
 void ARM::Savestate(Savestate* file)
                                ^~~~
/tmp/pamac-build-anton/melonds-git/src/melonds/src/ARM.cpp:164:32: note: suggested alternative: «fileno»
 void ARM::Savestate(Savestate* file)
                                ^~~~
                                fileno

Any tips?

**Comment by SIGMA-AX** [comment]
I get the exact same error messages but with Codeblocks on Windows 7 x64 as well and would like to know what the solution to it is.

**Comment by hcorion** [comment]
Please retest, this should now be fixed.
