### ISSUE TITLE
Runtime error on Windows

### ISSUE THREAD

**Issue by SIGMA-AX** [StapleButter/melonDS#256]
I managed to get the latest revision of MelonDS compiled successfully on Windows with Code::Blocks, but once I launch the .exe file I get this error:

![capture](https://user-images.githubusercontent.com/44013214/47161613-4cf36580-d2ea-11e8-8311-53aec965f306.PNG)

I tried putting in the .dll files from the 0.6b release into the binary directory, but I still received this same error when launching the .exe. It won't even run after building it in Code::Blocks.

Did I install the libraries or set-up MinGW incorrectly? This is what my global compiler settings look like:
![global compiler settings](https://user-images.githubusercontent.com/44013214/47161875-cc813480-d2ea-11e8-8e62-5c05e49af836.PNG)

I've also installed SDL2 through Msys2 MinGW 64-bit.

**Comment by StapleButter** [comment]
they say ScriptBreak is in Usp10.dll, so that's odd as fuck

**Comment by StapleButter** [comment]
ooooooo

" Starting with Windows 8: To maintain the ability to run on Windows 7, a
module that uses Uniscribe must specify Usp10.lib before gdi32.lib in its
library list."

I guess that's it. committing a quick fix

**Comment by StapleButter** [comment]
alright, try now?

**Comment by SIGMA-AX** [comment]
Yup! It compiles without any problems and I don't get any kind of weird error when I run it. Although it did crash a couple of times at first until I ran it as administrator. So that seems to have done the fix.
