### ISSUE TITLE
[Wi-Fi] Problems when trying to connect to melonAP 

### ISSUE THREAD

**Issue by SIGMA-AX** [StapleButter/melonDS#257]
I've run into some pretty interesting problems in regards to trying to set-up Wi-Fi in a game's WFC.  Before going into detail as to what the issues are, I am on Windows 7 x64 and:

- I have already installed Winpcap, that initializes fine when I check the the command line log when melonDS is running. 
- My main connection is solely through ethernet, and the adapter which I am using (Realtek PCIe GBE Family Controller) has had its driver updated to the latest version.

So at first, I received this error when trying to connect to the AP instead of the usual 20100 error:

![error 5200](https://user-images.githubusercontent.com/44013214/47189249-8f8d6000-d333-11e8-8c00-be49a231e40d.PNG)

I decided to do a little check on my network adapters and realized that I had a few of them on which served other purposes for other programs I suppose:

![adapters](https://user-images.githubusercontent.com/44013214/47189341-eeeb7000-d333-11e8-8896-847c90089dd7.PNG)

So I decided to see whether melonDS doesn't detect my main connection (Local Area Connection 2) and decided to disable the other adapters to see what would happen. It results in this crash:

![melonds wi-fi crash](https://user-images.githubusercontent.com/44013214/47189495-c4e67d80-d334-11e8-8f1f-1624111e0a71.PNG)

**Comment by StapleButter** [comment]
melonDS is hardcoded to use the second adapter, because that's what worked
on my laptop.

the feature is just unfinished.

**Comment by SIGMA-AX** [comment]
I see, guess it's just something that will be worked much later down the line.
