### ISSUE TITLE
Who Wants to Be a Millionaire (USA) flickering screens

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#259]
during the videos the bottom screen keeps flickering

**Comment by zeromus** [comment]
please cross reference https://github.com/TASVideos/desmume/issues/210 your issues

**Comment by StapleButter** [comment]
not quite the same deal here tho. tweaking DMA timing doesn't affect it.

but, it goes away if you disable threaded 3D.

this is some assfucking mindboggling issue where the VRAM mapping is being changed while the threaded renderer is still rendering.

**Comment by StapleButter** [comment]
VBLANK
[215] threaded render start
[243] MAP VRAM B. 8B->80
ARM9 DMA3 84003000 00 020691C4->06825980 49152 bytes 32bit
[261] threaded render done
VBLANK END
ARM9 DMA3 over
[003] MAP VRAM B. 80->8B

vcount=243 is quite early for unmapping VRAM, considering the renderer is running all the way to vcount=144 of the next frame.

I'd have to find out why the game is proceeding so early.

**Comment by zeromus** [comment]
I don't remember it having anything to do with 3d. It's decoding videos, that should all be on the cpu. Note that dma is 48K (the 2nd half of a screen). It switches it to be displayed after the DMA is done, I guess from a CPU buffer (decode output) to a VRAM buffer. I would further guess that it's scanline 243 at which the decoding is done. It maps it to CPU immediately after that for DMAing to vram. But I didn't look up what those vram mappings mean right now, that's just matching your log to what I remember it doing + common sense

**Comment by StapleButter** [comment]
so, it's taking ~23 scanlines to do its DMA transfer. normally, it does so right upon VBlank, so it's done just before the 3D renderer starts drawing shit.

but, sometimes, it needs to take a shit or whatever, and it's delayed until scanline 243, which is bad.

I guess I'll have to crack open the game code to find out what it's doing.

**Comment by StapleButter** [comment]
that might do it, yeah, but it's kind of a hack. the whole "unmap texture VRAM at scanline 243" isn't normal behavior. I quickly tested the same thing on hardware and it results in a big nice black line, so it's not something you should attempt doing.

**Comment by zeromus** [comment]
yeah, its a hack, but it's an accommodation for imperfect timing. the timing for any nds emulator is already hack city. Especially when it comes to timing big cache memory heavy cpu jobs, and....

...I guess in this case it's the cpu decode of the movie data that's taking too long? otherwise it should unmap the vram for dmaing to the vram before 3d rendering begins?

It's not too late for you to fiddle with your general cpu and memory timings, though. That ship has sailed with desmume

**Comment by zeromus** [comment]
:ballot_box_with_check: HLE the decoding, make it take 0 ticks, call it a day

**Comment by StapleButter** [comment]
with the latest timing work we have finally fixed this
