### ISSUE TITLE
Burnout Legends (USA) (En,Fr,Es)corrupt graphics

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#26]
Using MelonDS 0.2
after you choose your car the graphics are all corrupt
![burnout](https://cloud.githubusercontent.com/assets/2696404/25367604/48410542-29a9-11e7-9725-ab5dd73bfbd7.PNG)

**Comment by benderscruffy** [comment]
Ford Racing 3 (USA) also has the same problem

**Comment by StapleButter** [comment]
wow. it's even worse live

it's like something is filling the palettes with random data every frame

**Comment by StapleButter** [comment]
ok, it's fixed, it was actually display capture blending that was shitting itself


check the other affected games, they should be fixed too
