### ISSUE TITLE
Imagine - Teacher (USA) (En,Fr,Es,Pt) black backgrounds

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#260]
start a new game
click on any of the furniture
then when you come back to the room the background is gone and the furniture will flash
![teacher](https://user-images.githubusercontent.com/2696404/47599979-215c3380-d9ec-11e8-8a45-214ec2ee8335.PNG)

**Comment by zeromus** [comment]
see commit 66b5da1cdc5171f1f606e94f659811726cb4a39e in desmume but possibly later commits too. I haven't ever bothered to investigate exactly what's powered down in various situations, but it needs to be done (and isn't very hard). I suspect it's seemingly decided at random and cannot be predicted.

**Comment by StapleButter** [comment]
mh, thanks for the heads-up

I need to do hardware tests for this
