### ISSUE TITLE
Windows, MSYS2: GetPixelFormat error

### ISSUE THREAD

**Issue by Microeinstein** [StapleButter/melonDS#266]
I'm on Windows 7 using MSYS2 and I keep getting this error inside
this file: `libui_sdl/libui/windows/colordialog.cpp`
Here's the console output: https://pastebin.com/bMqUbhVS

Notes:
1. to get cmake to work I removed `if (UNIX)` sections and kept `WIN32` sections in `CMakeLists.txt`.
2. I replaced all `<pcap/whatever>` with `"proper_path/whatever"`

**Comment by StapleButter** [comment]
weird thing. maybe your DirectX SDK headers are outdated?

**Comment by StapleButter** [comment]
I addressed that, so

let's pray
