### ISSUE TITLE
Bejeweled 3 gets stuck in an endless loop

### ISSUE THREAD

**Issue by kurayami6** [StapleButter/melonDS#270]
Start the game and a screen appears saying the save data is corrupted and must be deleted.

![capture](https://user-images.githubusercontent.com/31968468/47998176-803f4c80-e152-11e8-9648-65c6eb3a5bea.PNG)

Press A and it will delete the save data. Then it goes back to first screen saying the data is corrupted. This continues forever.

![capture2](https://user-images.githubusercontent.com/31968468/47998218-a8c74680-e152-11e8-9621-092000e68bda.PNG)

Windows 7, i5, GTX 970. MelonDS 0.7

**Comment by StapleButter** [comment]
I guess you need to try with an existing savefile-- melonDS might be
failing to properly detect the type on the first run.

**Comment by benderscruffy** [comment]
all of the Bejeweled games are like this

**Comment by StapleButter** [comment]
http://kuribo64.net/get.php?id=0hYnKSkyPKqlheTq

just tested, runnin' fine

you might have an old failed save file that has the wrong size (melonDS 0.7 created a 1K file, the correct size is 8K), so try deleting it
