### ISSUE TITLE
No Analog

### ISSUE THREAD

**Issue by fancymelonub** [StapleButter/melonDS#271]
MelonDS wouldn't detect analog stick inputs from my Xbox One controller, even though other emus like Dolphin does.

**Comment by StapleButter** [comment]
do you mean, in the input dialog or in general?

**Comment by fancymelonub** [comment]
@StapleButter idk what you mean about "in general" but in the input dialog, it definitely doesn't detect my analog input

**Comment by fancymelonub** [comment]
also (going temporarily offtopic but) what compiler in codeblocks should i use to compile melonds

**Comment by StapleButter** [comment]
it's not very intuitive, but yeah. I should modify it so that it doesn't need button mappings to recognize an analog axis.

also you should get msys2 w/ mingw64

**Comment by fancymelonub** [comment]
Would the MSys in DevKitPro break if I install Msys2 separately?

**Comment by StapleButter** [comment]
addressed in last revision
