### ISSUE TITLE
Puzzler World 2 (USA) black screens

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#274]
after the loading screen nothing but black screens and music playing in the background

**Comment by StapleButter** [comment]
there's something acting up with depth test

it's using equal-mode depth test, and hacking that to always pass makes the graphics show up

**Comment by StapleButter** [comment]
as a side note: the game uses 'equal' depth test and gives all its polygons Z=1.0

which is why nothing was showing up
