### ISSUE TITLE
Just Sing! - Vol. 2 (Europe)  music buzzing

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#276]
the music is buzzing and not clear

**Comment by benderscruffy** [comment]
still happens in 0.7.2

**Comment by StapleButter** [comment]
blarg.

**Comment by StapleButter** [comment]
indeed that sounds pretty bad

**Comment by StapleButter** [comment]
the game seems to do some software audio decoding/decompression, and something seems to be miscalculated

**Comment by StapleButter** [comment]
hah. I knew this was some sort of CPU bug.

it's always fun seeing how these bugs manifest when you find them
