### ISSUE TITLE
Slight flickering in Nicktoons: Attack of the Toybots

### ISSUE THREAD

**Issue by SilasLaspada** [StapleButter/melonDS#279]
In Nicktoons: Attack of the Toybots, there is a slight flickering present in the title screen and some of the cutscenes. It is most visible on the title screen. It's not bad but it is noticeable.

**Comment by StapleButter** [comment]
probably a timing issue

**Comment by SilasLaspada** [comment]
Either it's fixed or it was just an optical illusion due to the spinning gears on the title screen. Either way, I don't really see it now.

**Comment by StapleButter** [comment]
also, keep in mind that the DS screens have a high latency, which tends to attenuate flickering

melonDS doesn't simulate that
