### ISSUE TITLE
Legend of the Guardians: The Owls of Ga'Hoole (USA) broken menu graphics

### ISSUE THREAD

**Issue by SilasLaspada** [StapleButter/melonDS#28]
In Legend of the Guardians: The Owls of Ga'Hoole (USA), the 3d graphics for the main menu seem a bit like they're on a bad trip. The in-game 3d seems to render fine though.

![ndsowls](https://cloud.githubusercontent.com/assets/24215969/25367704/a8d545be-2934-11e7-9933-0971e10ec7c8.JPG)

**Comment by benderscruffy** [comment]
same as #26

**Comment by SilasLaspada** [comment]
Fixed by commit d9afcc3
