### ISSUE TITLE
American Girl - Kit Mystery Challenge! (USA) buzzing music

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#281]
during the gameplay there is a buzzing with the music

**Comment by huckleberrypie** [comment]
At what point in the game does the music buzz? I do have a copy of the game with me so I can test it here on my end. Also, care to provide any steps to reproduce, and if possible a save state?

**Comment by benderscruffy** [comment]
when you very first start the game in the attic just walk around
why would u need a save state at the very beginning of the game ???

**Comment by huckleberrypie** [comment]
> 
> 
> when you very first start the game in the attic just walk around
> why would u need a save state at the very beginning of the game ???

Well I'm asking for a save state as you initially didn't mention where does the buzzing take place.

**Comment by StapleButter** [comment]
"buzzing" sounds like it's crackling, like what happens when melonDS runs too slow

this is more like it's just playing random/corrupted crap instead of actual music

**Comment by StapleButter** [comment]
some channels use repeat mode 3, which GBAtek helpfully notes as 'prohibited' without actually saying what it does. so, more testing to do there.

anyway, the garbage somehow makes it to the speakers even if I disable all channels. wtf

**Comment by StapleButter** [comment]
why doesn't the game just stop its goddamn channel instead of setting it to mode 3 (which achieves nothing on channels 0-7) is beyond me, but oh well, it's fixed now
