### ISSUE TITLE
Brain Age 2 - More Training in Minutes a Day! (USA) (En,Fr,Es) fails to boot

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#29]
using MelonDS 0.2
comes up with the message 
Unable to save data Turn off the DS and reinsert the Game Card

![](https://cloud.githubusercontent.com/assets/26326692/25073772/d80775d4-22ed-11e7-91e3-988a49d40d62.png)

**Comment by benderscruffy** [comment]
Dancing with the Stars - We Dance! (USA) has the same problem

**Comment by endrift** [comment]
IIRC this was because out-of-bounds SPI Flash reads/writes should wrap, not get blocked or return hi-z

**Comment by StapleButter** [comment]
That's what melonDS does. But it may be detecting the wrong save type. Try running the game with no save file, see what the console says and compare it to a database.

**Comment by benderscruffy** [comment]
it says the same with or without a save

**Comment by einstein95** [comment]
Brain Age 2 was being incorrectly identified as EEPROM, when it should be Flash. This has since been fixed, most likely by 7ac538d5d2dd4ad44eab9f44d0b016e38ac51d0e.
Dancing With The Stars: We Dance's problem is unrelated.

**Comment by benderscruffy** [comment]
works in Melon DS 0.3
