### ISSUE TITLE
Game not saving in Ring of Fates & Echoes of Time

### ISSUE THREAD

**Issue by extherian** [StapleButter/melonDS#291]
Saving the game is not possible in Final Fantasy Crystal Chronicles: Ring of Fates & Final Fantasy Crystal Chronicles: Echoes of Time. The game will report that the save has been successful, however no save file will be created in the ROM folder and there will be no save to load when the game is booted up again.

All other DS games I own are saving normally with melonDS, which makes me think these games are doing something strange in order to save that other DS games don't do.

**Comment by StapleButter** [comment]
"Also, melonDS will not create an INI file when run. This causes a number of problems, as without an INI file melonDS can only be run from the command line. I have full permissions for the folder melonDS is in as well as my ROM folder, and fixed this issue by creating the INI file myself in a text editor."

that's weird. haven't been able to reproduce it here-- it not only runs fine but creates melonDS.ini when closing.

**Comment by extherian** [comment]
It's entirely possible the INI issue is my fault. Since melonDS doesn't have an installer, I created a melonDS folder manually in Program Files and gave myself full read/write permissions to it, under the assumption that melonDS would inherit those permissions when it ran and create an INI file for itself.

I think that the saving issues are down to melonDS not recognising that romlist.bin is present, which makes me think some kind of path issue is at work, like what caused melonDS not to recognise the BIOS files before. You might want to try running melonDS somewhere other than your home directory and see if it still works correctly.

Anyway, I managed to get the games to save properly by dumping raw .sav files from the game cards using my homebrewed 3DS and TWLSaveTool. Once the correct .sav files were present in the same folder as the ROMs, the games can be saved as normal, though the flickering is still present.

**Comment by StapleButter** [comment]
https://docs.microsoft.com/en-us/sysinternals/downloads/procmon

someone recommended this to track which paths melonDS is trying to access

I don't quite see which part of melonDS would fail given spaces in paths, unless GetCommandLineW() was broken in Windows 10

**Comment by benderscruffy** [comment]
@extherian 
can you test this again with 0.7.3 please

**Comment by extherian** [comment]
Hey, sorry for taking so long to reply. I can confirm that both Ring of Fates and Echoes of Time are saving correctly. The graphical glitches that were present previously are now gone as well.

Feel free to close this issue as there is nothing more that needs to be fixed.

**Comment by benderscruffy** [comment]
you can close this issue yourself (close and comment button)
