### ISSUE TITLE
New Super Mario Bros 1-Cannon World Map Flicker

### ISSUE THREAD

**Issue by XXLuigiMario** [StapleButter/melonDS#295]
Part of the W1 cannon keeps flickering with a black texture on MelonDS 0.7.1.

![Flicker](https://user-images.githubusercontent.com/7153662/49836275-52c56e80-fda2-11e8-8d1a-87a179f0b575.gif)

**Comment by StapleButter** [comment]
it's weird because I haven't seen it happen at all here. which ROM version/region?

**Comment by XXLuigiMario** [comment]
European version (NTR-A2DP-EUR).

![rom](https://user-images.githubusercontent.com/7153662/49860967-1c680d80-fdfb-11e8-9f6e-2fc5462248f5.png)

**Comment by StapleButter** [comment]
confirmed. the ROM I was using was the USA one.

**Comment by wyatt8740** [comment]
Could it be related to this problem I just had when I tested out Pokémon Diamond? Using the latest git sources, Debian Sid, with a clean ROM I dumped myself and verified the checksum for.

![10 second recording of flickering sprite in Diamond](https://i.imgur.com/ixQYzs0.gif)

(Should I open a separate ticket?)

**Comment by StapleButter** [comment]
yes, it's the same issue, it stems from the timing renovation.

also, you don't have to worry about that :P
