### ISSUE TITLE
Etrian Odyssey: Top and bottom screen swapped/disappear

### ISSUE THREAD

**Issue by xdanieldzd** [StapleButter/melonDS#297]
Etrian Odyssey has issues with the top and bottom screens being swapped and disappearing at various times in melonDS 0.7.1, while it appears to work fine in 0.7.

During the intro, the company logos and later the game logo should appear on the top screen, with the bottom screen showing some story text. The title screen should show the game logo on the top, menu on the bottom, and the 3D background over both screens. In 0.7.1, it's... like this.

![EO1 in 0.7.1](https://user-images.githubusercontent.com/7199225/49872968-f3f00b80-fe1a-11e8-91f5-2a8e9f5ffd01.gif)
(Intro first, then title screen, then trying to load a nonexistent save game a few times, to show some "random" screen swapping, then starting a new game.)

It appears to be working fine in-game for the most part, but ex. during guild and character creation, screens get swapped and disappear as well. Might in that case be related to the on-screen keyboard, tho I can't say for sure.

Footage from the European version; the Japanese one behaves the same way, so I'd assume the US one does as well.

**Comment by StapleButter** [comment]
amusingly enough, the USA version is fine

was the same deal with NSMB's cannon

this is a different kind of issue tho
