### ISSUE TITLE
Eledees - The Adventures of Kai and Zero (Europe) (En,Fr,De,Es,It) corrupt graphics

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#30]
Using MelonDS 0.2
the graphics on both screens are corrupt

**Comment by StapleButter** [comment]
Have a screenshot of the corruption?

**Comment by benderscruffy** [comment]
![eledees](https://cloud.githubusercontent.com/assets/2696404/25416920/278d9bc4-2a73-11e7-90b9-9d4765c3bbfc.PNG)

**Comment by StapleButter** [comment]
that's interesting to say the least. looks like the TV decoder broke :P

**Comment by StapleButter** [comment]
fixed as of 2273bd2ea46c1d53a775d0f11bf902e1b3bb125b
