### ISSUE TITLE
Club Penguin: Herbert's Revenge - Music doesn't play

### ISSUE THREAD

**Issue by noddy360** [StapleButter/melonDS#300]
The US release of this game boots and it's playable, but the music doesn't play. The sound effects do play, but not the music.
Also the European release has a save error after boot. It says "The save data could not be accessed." on a black screen.

**Comment by StapleButter** [comment]
the EUR version uses 4K EEPROM, unlike the USA version (and unlike what the database says, so it's time to correct that)
