### ISSUE TITLE
Pokemon: Sprites glitching rapidly

### ISSUE THREAD

**Issue by Jordy3D** [StapleButter/melonDS#303]
Not sure when this bug was introduced, but this is the first I've noticed this on this game so I assume it's from the newest build.

Sprites seem to just want to not behave.
![dawnpls](https://user-images.githubusercontent.com/19144524/49987799-c0eb7a80-ffc8-11e8-8723-63872f412cd4.gif)
![spriteswhy](https://user-images.githubusercontent.com/19144524/49987802-c1841100-ffc8-11e8-9d41-47435c5db26a.gif)

**Comment by StapleButter** [comment]
this is already known and I hope to fix it for 0.7.2

**Comment by Jordy3D** [comment]
Ah, apologies, thanks for the response!

**Comment by StapleButter** [comment]
regardless, you can try with the last revision. it should be fixed.
