### ISSUE TITLE
Madden NFL 09 (USA) cannot save

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#306]
using 0.7.2
stuck on first screen data cannot be written
![madden 09](https://user-images.githubusercontent.com/2696404/50051105-10f04b80-0147-11e9-88e3-71f4cdf2e411.PNG)

deleted all my old saves and problem still happens

**Comment by StapleButter** [comment]
probably an error in romlist.bin. providing a working savefile should do the trick, atleast until we correct it.
