### ISSUE TITLE
Violent Flickering in 0.7.2

### ISSUE THREAD

**Issue by JMC47** [StapleButter/melonDS#308]
Every single game I've tried to load has a violent "white" flicker between frames.  It's not present in 0.7.1.

It happens on both top and bottom screen and is incredibly straining to the eyes.  I tested Etrian Odyssey U.S., PAL, and All regions of The Legend of Zelda: Spirit Tracks, as those are the games I have on hand.

The higher the framerate that the game runs, the more violent the flickering becomes.  If you pause the emulator it never stops on a white frame.  I assume this is some kind of bug on my end (as Etrian Odyssey was mentioned as fixed...) but I've tried every setting and cannot get it to go away.  0.7.1 works fine with the same settings.

**Comment by StapleButter** [comment]
mh

did you map the lid hotkey to a joystick control?

**Comment by JMC47** [comment]
I didn't map it whatsoever... is it on one by default?

**Comment by StapleButter** [comment]
it shouldn't be. be sure to check it.

something must be spuriously triggering the lid close/open command, that's all I can see

**Comment by JMC47** [comment]
That seems to be a reasonable assumption but I don't have it set.  I'll try unsetting everything and manually setting it.

**Comment by JMC47** [comment]
It appears the default setting for "none" is -1, which triggers the an axis on my controller.

**Comment by JMC47** [comment]
Setting it to a button instead of -1 fixes the issue, but I don't know if this is a really good default behavior...

**Comment by StapleButter** [comment]
was an oversight on my part, btnid=-1 caused it to read out of bounds. I'm a derp

redownload it, should be fixed
