### ISSUE TITLE
Pokemon HeartGold - audio crackling issue

### ISSUE THREAD

**Issue by abcdjdj** [StapleButter/melonDS#309]
Hi StapleButter,

I noticed that even after the timing renovation commits, the audio crackling issue is still persistent in Pokemon HeartGold (occurs even on [https://github.com/StapleButter/melonDS/commit/4a36193cabc86fbe07b6b5807e4441ffd72ed5c3](https://github.com/StapleButter/melonDS/commit/4a36193cabc86fbe07b6b5807e4441ffd72ed5c3)). Could you please look into it?

Thanks!

**Comment by StapleButter** [comment]
is the game running at a solid 60FPS? if not, there may be crackling from that

**Comment by abcdjdj** [comment]
A perfect diagnosis. My laptop can't play it at a solid 60 fps. Turns out the i5 6200U is really crappy :(
I guess things will run better once the hardware renderer is implemented. Anyway, thanks a ton! I think I can close this now.

**Comment by StapleButter** [comment]
side note: we might implement some kind of timestretching later on to avoid that, too

but for now it's not too high on the priority list
