### ISSUE TITLE
Petz Catz Clan (USA)

### ISSUE THREAD

**Issue by SilasLaspada** [StapleButter/melonDS#31]
In Petz Catz Clan (USA) the cats don't always know where the ground starts. They can sink so far down that they're completly invisible, other times they just don't seem to have legs.

![ndscatz](https://cloud.githubusercontent.com/assets/24215969/25394266/d6031cda-299a-11e7-84bf-20577f39ef30.JPG)

**Comment by StapleButter** [comment]
same as #15, #24, and some others. zbuffer shit

**Comment by StapleButter** [comment]
should be fixed by da31af92029af5f9db3c9fcc226414e3789f2682

**Comment by SilasLaspada** [comment]
It is indeed fixed!
