### ISSUE TITLE
Viewtiful Joe - Double Trouble! (Europe) crashes out emulator

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#310]
using 0.7.2
go to the menu screen (New Game , Load Game and Options )
just let it sit there and when it goes to the demo it crashes out the emulator

**Comment by StapleButter** [comment]
that doesn't sound too good

**Comment by StapleButter** [comment]
seems to be some case of degenerate polygon where somehow one of the vertices is NULL
