### ISSUE TITLE
Dark Spire, The (USA) missing map

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#311]
using 0.7.2
during the game when you press Y button it is supposed to bring up the map
![spire](https://user-images.githubusercontent.com/2696404/50198997-70d63480-0389-11e9-852c-a31042fef191.PNG)
here is how it is supposed to look
![spire proper](https://user-images.githubusercontent.com/2696404/50199003-7b90c980-0389-11e9-9a56-b5d05c5a5f0d.png)

**Comment by StapleButter** [comment]
do you have a savefile where I can get to this point quickly?

**Comment by benderscruffy** [comment]
just choose a party then basic training

**Comment by StapleButter** [comment]
yeah well, I don't have the patience to go through the 'basic training'

just give me a savefile. blarg

**Comment by benderscruffy** [comment]
there is a problem when you go to load your save state
it says that it is corrupt
![dark](https://user-images.githubusercontent.com/2696404/50225897-b96b0d80-03dc-11e9-96ed-9f7974ed8de6.PNG)

**Comment by StapleButter** [comment]
oh. I get it now :P 

I'll get to this game a bit later

**Comment by StapleButter** [comment]
does saving still break with the last romlist.bin?

**Comment by StapleButter** [comment]
also, latest revision might fix it
