### ISSUE TITLE
nocashPrint support

### ISSUE THREAD

**Issue by TheGameratorT** [StapleButter/melonDS#315]
As the emulator now has support for nocash printing like console I wonder if you could implement support for nocashPrint function like in Desmume. I would really appreciate it as I'm a Mario Vs Luigi hacker and that would facilitate things alot.

I tested on melonDS 0.7.2 and I couldn't get it to work.

This is the print function btw. You may already know about it.
https://github.com/Dirbaio/ASMPatchTemplate/blob/master/source/print.s

**Comment by StapleButter** [comment]
if you're using the Release version, you need to run it from cmd to get console output.

other than that, your code should be working as intended.

**Comment by TheGameratorT** [comment]
I recorded a video showing up the problem.
https://drive.google.com/open?id=19srQVp_LGyZMuWhlyChzhFZogZyJpssa

**Comment by StapleButter** [comment]
well apparently this also works in ARM mode

I assumed it only worked in THUMB, that's why
