### ISSUE TITLE
Lego Batman (USA) minor graphical glitch

### ISSUE THREAD

**Issue by SilasLaspada** [StapleButter/melonDS#32]
In Lego Batman (USA) the circle that is supposed to surrond the active character icons has folded in on itself and looks more like of a phase of the moon.
![ndsbat](https://cloud.githubusercontent.com/assets/24215969/25401328/b0c552c2-29b2-11e7-89aa-4ef6cc0e01be.JPG)

**Comment by StapleButter** [comment]
interesting glitch to say the least

**Comment by StapleButter** [comment]
maybe 2273bd2ea46c1d53a775d0f11bf902e1b3bb125b fixed it, pls retest if possible

**Comment by SilasLaspada** [comment]
No, it is not fixed yet. :(

**Comment by einstein95** [comment]
Can confirm a non-fix as of da31af92029af5f9db3c9fcc226414e3789f2682.

**Comment by StapleButter** [comment]
fixed. was actually unrelated to the 3D engine, I had forgotten to implement xflip for bitmap sprites.
