### ISSUE TITLE
Baby Pals (Europe) missing music and sound fx and  missing graphics

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#320]
using 0.7.2
on the title screen the baby is missing 
the music and sound fx are also missing
this is how desmume fixed it
https://sourceforge.net/p/desmume/bugs/753/
![baby](https://user-images.githubusercontent.com/2696404/50332946-abcd9900-053e-11e9-8233-40fe408c494e.PNG)

**Comment by StapleButter** [comment]
"for the record, game was booting at volume 0. that was a bug caused by using 0x00 for uninitialized save data instead of 0xff"

really?? what a pile of shoddy programming.

**Comment by StapleButter** [comment]
see if the latest revision fixes it

**Comment by benderscruffy** [comment]
all issues fixed in 0.7.3
