### ISSUE TITLE
Logic Machines (Europe) cannot save

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#324]
using 0.7.2
after you complete the first level you cannot save it
![logic](https://user-images.githubusercontent.com/2696404/50336158-5b5b3900-0548-11e9-8ee5-3efcab1f67c5.PNG)

**Comment by StapleButter** [comment]
http://melonds.kuribo64.net/comments.php?id=71

pls redownload romlist.bin, delete any bad savefiles, and update your issues accordingly if those games were fixed

**Comment by StapleButter** [comment]
this particular game still shits itself, because the CRC for it isn't in the DB

in 0.7.3 we will be using game codes so this will not be an issue

**Comment by takeshineale128** [comment]
> http://melonds.kuribo64.net/comments.php?id=71
> 
> pls redownload romlist.bin, delete any bad savefiles, and update your issues accordingly if those games were fixed
error when trying to download the file

**Comment by benderscruffy** [comment]
fixed
