### ISSUE TITLE
Sims 2, The - Apartment Pets (Europe) corrupt faces when blinking

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#327]
using 0.7.2
when you edit your character  when they blink  it is not right
![pets](https://user-images.githubusercontent.com/2696404/50337437-1507d900-054c-11e9-9665-42fb7098daea.PNG)

**Comment by StapleButter** [comment]
is this one also a 0.7.1/0.7.2 regression?

**Comment by benderscruffy** [comment]
it was even worse off in the earlier versions
![face](https://user-images.githubusercontent.com/2696404/50620815-cf301500-0f3c-11e9-891a-d1256d2d7860.PNG)

**Comment by StapleButter** [comment]
holy fucking shit.

not sure what the game is doing there. hopefully not some ass-stinking timing issue.

**Comment by StapleButter** [comment]
ok seems that is fixed in latest revisions
