### ISSUE TITLE
Spore Hero Arena (Europe) cannot save

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#328]
using 0.7.2
![spore](https://user-images.githubusercontent.com/2696404/50337664-d1fa3580-054c-11e9-83cc-59a2ab66b401.PNG)

**Comment by benderscruffy** [comment]
still the same problem

**Comment by StapleButter** [comment]
'ts because it fails to find it in the old CRC-based list.

new list is based on gamecodes and sucks less.
