### ISSUE TITLE
Hamsterz Life (Europe) hamster is glitchy

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#329]
using 0.7.2
on the hamster selection screen the hamsters keep flickering and glitchy lines 
![hamster](https://user-images.githubusercontent.com/2696404/50345662-d59cb500-056a-11e9-98ea-7cb1dd6e314c.PNG)

**Comment by StapleButter** [comment]
that's the government's hamster leash all the conspirationists keep talking about :P

**Comment by benderscruffy** [comment]
heheh good one :P

**Comment by StapleButter** [comment]
latest revision successfully foiled the government's evil plans and fixed that issue
