### ISSUE TITLE
Wild West, The (USA) corrupt graphics on title screen

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#331]
using 0.7.2
![wild](https://user-images.githubusercontent.com/2696404/50348086-ba35a800-0572-11e9-949a-29569663eb49.PNG)

**Comment by StapleButter** [comment]
that doesn't look too good

likely to be an interesting bug behind this shit

**Comment by StapleButter** [comment]
yeah well indeed that seems to be a CPU bug, like, the tilesets for those graphics aren't being decompressed properly

**Comment by StapleButter** [comment]
turns out it wasn't in the decompression. borp
