### ISSUE TITLE
Coropata (Japan) cannot save

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#336]
using 0.7.2
stuck on the first screen
![coro](https://user-images.githubusercontent.com/2696404/50367513-b5e1ad00-05bb-11e9-9adf-bf6059e945bb.PNG)

**Comment by kurayami6** [comment]
Are you sure it's a problem with saving? It says "Couldn't read data. Please turn off the power and reinsert the card"

**Comment by benderscruffy** [comment]
yes

**Comment by benderscruffy** [comment]
still has the same problem

**Comment by benderscruffy** [comment]
fixed in 0.7.3
