### ISSUE TITLE
Glitches on the title screen of Infinite Space (USA)

### ISSUE THREAD

**Issue by kurayami6** [StapleButter/melonDS#339]
The ship is constantly flickering and popping in and out of existence. 

![capture](https://user-images.githubusercontent.com/31968468/50435149-2d089f80-0934-11e9-95e5-7b41d53c5db4.PNG)

**Comment by StapleButter** [comment]
does this happen on older melonDS versions?

**Comment by kurayami6** [comment]
Worked fine up until 0.7. As of 0.7.1 It only showed half the screen but the ship rendered fine. Then in 0.7.2 it showed both screens and the ship was a flickering mess.

![capture](https://user-images.githubusercontent.com/31968468/50544448-c80dbc00-0c49-11e9-8185-3a90b56305bc.PNG)

**Comment by StapleButter** [comment]
ok well this can get the nice label of zrfqsfgdfgfdhdgd

**Comment by kurayami6** [comment]
Fixed as of 0.7.3

![capture](https://user-images.githubusercontent.com/31968468/50727131-6928d500-116a-11e9-8d42-5ced101a9072.PNG)
