### ISSUE TITLE
Lego Harry Potter: Years 5 - 7 (USA) minor graphical glitch

### ISSUE THREAD

**Issue by SilasLaspada** [StapleButter/melonDS#34]
In Lego Harry Potter: Years 5 - 7, the active spell should be circled by a moving line. There is no line at all in MelonDS. 
![ndshp2](https://cloud.githubusercontent.com/assets/24215969/25633189/8dd46eca-2f33-11e7-8e4f-71a4124948e3.JPG)

**Comment by StapleButter** [comment]
may be related to the layering of 3D elements (Y-sort)

**Comment by SilasLaspada** [comment]
Issue still present in 5991034.

**Comment by windwakr** [comment]
Here's a pic of the objects from no$gba's vram viewer. When you start the game the orange spell(in right side of pic) is selected, and the yellow circle(left side of pic) will be on top of it and spinning around.
![untitled](https://user-images.githubusercontent.com/284886/27885640-a1cc8a8e-61a6-11e7-9350-00650fbf277d.png)

**Comment by StapleButter** [comment]
fixed
