### ISSUE TITLE
Little Red Riding Hood's Zombie BBQ stuck on first screen

### ISSUE THREAD

**Issue by kurayami6** [StapleButter/melonDS#340]
Game stays on this screen forever.

![capture](https://user-images.githubusercontent.com/31968468/50447631-8db5cd80-0970-11e9-9abb-aae6f7e60e6c.PNG)

**Comment by benderscruffy** [comment]
still has the problem

**Comment by StapleButter** [comment]
pls retest on 0.7.3

**Comment by kurayami6** [comment]
Fixed as of 0.7.3
