### ISSUE TITLE
Pokémon Mystery Dungeon: Explorers of Sky save issues

### ISSUE THREAD

**Issue by Ammako** [StapleButter/melonDS#344]
Continued from 0.6b

With the changes from 0.7.1, tested with 0.7.2, the game no longer gives an error when saving, but 8 KB of essentially blank data is being generated as a save file (this game uses 128 KB EEPROM [<sup>[1]</sup>](https://github.com/TuxSH/TWLSaveTool/commit/e9dad7e7ff094bc94b46efb5839ec76f062736ad#diff-359261da2d9f0f78c3917002f41732e0R128) [<sup>[2]</sup>](https://drastic-ds.com/viewtopic.php?p=4327&sid=e016d7e3164e7234886fb5b7c7e3780c#p4327), whereas Advanscene has it as 256 KB Flash for whatever reason.)

Providing an existing working save file does not work. The game does not recognize it.
I haven't checked to see if the AR code save hack still works, but we shouldn't be relying on that anyway.

I can attach said 8KB save file along with a proper save file if you'd like to look at it. It's likely that this game goes much further beyond simple save type issues, it's a really weird one.

**Comment by StapleButter** [comment]
interestingly it worked before with 256KB savefiles, because the protocol for 128K EEPROM is compatible with FLASH types.

and now that makes me doubt, is that EEPROM or FLASH? doesn't matter a lot tho as long as we get the size right.

**Comment by Ammako** [comment]
Not sure, but the people who worked on TWLSaveTool consistently refer to it as EEPROM, and given that they got PMD: EoS save file backup/restore working where both Rudolph's tool and savegame_manager always had issues, I'm tempted to trust that they know what they're talking about.

Though if the specific save type doesn't matter for melonDS, and only the file size counts, then I guess that doesn't really matter, yeah.

**Comment by StapleButter** [comment]
I guess it would matter if the game wanted to use some of the extra commands FLASH memory supports, but it doesn't seem to do so, so... yeah.

**Comment by StapleButter** [comment]
actually re: EEPROM vs FLASH

command 0x02 is used to write data on EEPROM, but on FLASH that command erases data (or something like that)

I guess that explains why some melonDS revisions could load some savefiles properly but never save

**Comment by Ammako** [comment]
Sounds convenient. Well, at least the flashcart save type databases should be more or less accurate, and if a game did have EEPROM vs. Flash wrong it'll probably be easy to figure out that it's wrong.
