### ISSUE TITLE
American Girl games (Julie Finds A Way/Kit Mystery Challenge) do not boot

### ISSUE THREAD

**Issue by huckleberrypie** [StapleButter/melonDS#36]
Both games, which essentially run off the same engine, end up with an "unknown arm7/arm9 read32 00B74AB0 | 00B74AB0" on the debug output console. Other than that, it's just a black screen.

Edit: A number of other games, like Monster Trucks DS, are also exhibiting the same issue.

**Comment by StapleButter** [comment]
this sounds like you forgot the firmware/BIOS

**Comment by huckleberrypie** [comment]
Strange, I already have it present on the MelonDS folder. :/

**Comment by StapleButter** [comment]
interesting bugs there

do the same ROMs work on hardware though? just making sure they aren't bad dumps

**Comment by huckleberrypie** [comment]
Yeah the ROMs I got do work fine on both real hardware and emulators, so there's no way the games I tried to load are toast.

**Comment by StapleButter** [comment]
just checked AG Kit Mystery Challenge on the latest rev, and it seems to run fine, so it seems the bug got fixed in the meantime.

did you try booting those games directly? the bug may just be that one bug that made firmware boot unstable.

**Comment by huckleberrypie** [comment]
Yeah, both games now work once I booted them directly. There's another problem though that has something to do with model clipping. In a number of scenes objects tend to get cut off such as in this screenshot:
![48 fps - melonds 0 2](https://cloud.githubusercontent.com/assets/5564327/26280290/47badf70-3dff-11e7-963c-08f34bfc5a02.png)

**Comment by StapleButter** [comment]
I'll ask you to test again when 0.3 is out. I think this is that Z-buffering issue that has since been fixed.

**Comment by huckleberrypie** [comment]
Sure thibg mqn, I'll let you know how the games fare with the next release. Oh and is this on a dynarec or are things still interpreted in some way?

**Comment by StapleButter** [comment]
it's still an interpreter
