### ISSUE TITLE
Plants Vs. Zombies (USA) missing text in the menu

### ISSUE THREAD

**Issue by SilasLaspada** [StapleButter/melonDS#38]
Most of the text in the main menu of Plants vs. Zombies is missing. 
![ndspvz](https://cloud.githubusercontent.com/assets/24215969/26005826/7c5f5454-36f7-11e7-80c9-d7586652b063.PNG)

**Comment by SilasLaspada** [comment]
This appears to only affect the bottom screen, because when the scene scrolls down, the text and graphics appear to render correctly when they reach the top screen.
![ndspvz2](https://cloud.githubusercontent.com/assets/24215969/26563129/8bf730d0-448a-11e7-9ee2-14d4aed7f010.PNG)

**Comment by StapleButter** [comment]
that's odd to say the least

**Comment by SilasLaspada** [comment]
If you finish a level and go back to the menu, everything is displayed correctly. Huh.
