### ISSUE TITLE
Zubo (EUR) can't move around at all

### ISSUE THREAD

**Issue by SilasLaspada** [StapleButter/melonDS#39]
You can't move in Zubo (EUR).  The character is supposed to move to where the touchscreen is clicked, but it just turns in that direction and doesn't actually move. The console is spammed with "!! PROJ MATRIX STACK UNDERFLOW" followed by "unknown GPU read16 04001010" and "unknown GPU read16 04001012".

**Comment by SilasLaspada** [comment]
I found the source of this issue, and it is really interesting. It turns out that this game let's you blow away stuff like cobwebs using the microphone. It lets you do this at any time. Now, the real problem is that you can't move while blowing. From what I can tell (please correct me if I'm wrong) MelonDS doesn't actually utilize a microphone yet, so it just tells the games that the mic is used constantly (to let you progress through puzzles, I assume). This means that in Zubo, it thinks that you're blowing into the mic the whole time, and thus doesn't let you move. I assume this can't be properly fixed until MelonDS properly picks up sounds from a microphone. But hey, at least we know why it doesn't work! :P

**Comment by StapleButter** [comment]
https://github.com/StapleButter/melonDS/blob/master/src/SPI.cpp#L411

microphone reads return 0xFFF, which might make the game think that there's noise (I guess the silence level is supposed to be around 0x800).

good find there.

**Comment by Brian151** [comment]
Maybe you could implement this is a way similar to desmume. I forget all the specifics, as I only ever had to use it once, but Desmume has an auto-mic system that can be turned on/off, and has a few different configurations.

**Comment by SilasLaspada** [comment]
I can confirm that changing that value to 0x800 fixes the issue. Of course that means that you can't do anything that needs a microphone, but it's a start. Do you think you could make a hotkey to switch between on/off for the mic like Brian151 said? That would probably the simplest solution that isn't a hack.

**Comment by SilasLaspada** [comment]
"Fixed" as of latest commit. You can't do any puzzles that require a mic, but at least you can move around.
