### ISSUE TITLE
Scribblenauts seems to fail to save

### ISSUE THREAD

**Issue by StapleButter** [StapleButter/melonDS#40]
ditto

the melonDS 0.2 screenshot of it has a blank player name. player/save names keep blanking themselves.

**Comment by SilasLaspada** [comment]
I found the problem. Just like for Phineas and Ferb: Across the 2nd Dimension, MelonDS generates an incorrect save file.  The one generated is 8 KB, while a proper one from a real DS is 64 KB. I verified that the 64 KB one saves properly. I attached a working save file just in case you need it.
[SuperScribblenautSaveFile.zip](https://github.com/StapleButter/melonDS/files/1036189/SuperScribblenautSaveFile.zip)

**Comment by StapleButter** [comment]
well, thanks for the heads-up
