### ISSUE TITLE
Lego Star Wars: The Complete Saga (USA) missing some effects

### ISSUE THREAD

**Issue by SilasLaspada** [StapleButter/melonDS#41]
This game is missing some effects in the bottom screen. I added an extra screenshot from DeSmuME to compare. 

DeSmuME: Renders it properly as far as I can tell.
![desmumestarwars](https://cloud.githubusercontent.com/assets/24215969/26333668/95d824ba-3f1c-11e7-8a68-bfe25c3d41e5.PNG)

MelonDS: Does not render the effects
![melonstarwars](https://cloud.githubusercontent.com/assets/24215969/26333669/9ae339ea-3f1c-11e7-9e65-f134363d0a20.PNG)

**Comment by DarkSwan86** [comment]
This bug is still present on ad58a68
