### ISSUE TITLE
Lego Harry Potter: Years 1-4 (USA) missing menu graphics

### ISSUE THREAD

**Issue by SilasLaspada** [StapleButter/melonDS#42]
This game is missing some graphics in the menu on the bottom screen. 

DeSmuME renders it correctly as far as I can tell.
![desmumehp](https://cloud.githubusercontent.com/assets/24215969/26358876/25206802-3f91-11e7-9d3f-9948ea0b3bdc.PNG)

MelonDS does not.
![melonhp](https://cloud.githubusercontent.com/assets/24215969/26359972/1be0c130-3f94-11e7-811f-4b929dfd233d.PNG)

**Comment by StapleButter** [comment]
may be fixed by the latest commits; have yet to check

**Comment by SilasLaspada** [comment]
It has been fixed by the latest commit!
