### ISSUE TITLE
Moero! Nekketsu Rhythm Damashii - Osu! Tatakae! Ouendan 2  - Map Screen Broken

### ISSUE THREAD

**Issue by gourdcaptain** [StapleButter/melonDS#47]
On MelonDS 0.3 (testing on Arch Linux x64), the map screen in "Moero! Nekketsu Rhythm Damashii - Osu! Tatakae! Ouendan 2" is heavily broken with only parts of what should be being displayed, including missing 3D elements and sprites.

Correct Map
 (taken from Desmume due to an inability to capture from actual DS):
![ouendan 2 - correct map](https://cloud.githubusercontent.com/assets/7662067/26808015/16deb4aa-4a28-11e7-8ac2-44aca990e8da.png)

MelonDS 0.3's Broken Map (different top screen is due to slightly more save progress in MelonDS):
![ouendan 2 - melonds 0 3 incorrect map 1](https://cloud.githubusercontent.com/assets/7662067/26808028/2e579ea8-4a28-11e7-975d-6c64f31366b9.png)
![ouendan 2 - melonds 0 3 incorrect map 2](https://cloud.githubusercontent.com/assets/7662067/26808032/34f84b2c-4a28-11e7-921e-2493c368d6b8.png)

**Comment by gourdcaptain** [comment]
Trying out a git build: f749ede319388e3cacedd69fe1e6536bc596102c
Issue also exists in up-to-date git version.

**Comment by gourdcaptain** [comment]
...wrong button.

**Comment by DarkSwan86** [comment]
I can confirm the game is fixed on ad58a68

**Comment by gourdcaptain** [comment]
Confirmed as well.
