### ISSUE TITLE
Who Wants to Be a Millionaire (USA) missing music and voices

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#52]
there is no music and the voices come up as static

**Comment by benderscruffy** [comment]
Big Mutha Truckers (USA) has the same problem no music or voices

**Comment by DarkSwan86** [comment]
Who Wants to Be a Millionaire (E) now has music and voice but Big Mutha Truckers (E) is still silent on ad58a68

**Comment by benderscruffy** [comment]
fixed
