### ISSUE TITLE
Pokemon Mystery Dungeon - Explorers of Time/Darkness/Sky (U) - black screen after the opening cutscene

### ISSUE THREAD

**Issue by Hexagon12** [StapleButter/melonDS#53]
First of all: thank you for making a really good DS emulator!

And second: Pokemon Mystery Dungeon - Explorers series (all 3 of them) produce a black screen after the opening cutscene / movie on MelonDS 0.3. Everything before that appears perfect (no video, sound glitches). The game is unplayable because of this. Getting a save file also doesn't help.

I've attached a log file for you to check out.
[log.txt](https://github.com/StapleButter/melonDS/files/1057605/log.txt)

**Comment by DarkSwan86** [comment]
I've tested ad58a68 and i can go ingame (i've tried some battles) without any problem, can you recheck it?

**Comment by Hexagon12** [comment]
I'm pretty sure that wasn't the commit that fixed it, but ad58a68 works. Can someone bisect where it was fixed?

**Comment by StapleButter** [comment]
probably 4ffb2177913ed97c1e0705f040002acff8e0efc0
