### ISSUE TITLE
Mario Kart 

### ISSUE THREAD

**Issue by Heoz** [StapleButter/melonDS#54]
So is wifi going to be searched automatic or need manual setup :O

**Comment by StapleButter** [comment]
what

**Comment by Heoz** [comment]
When you get in some game menu with network option there is a search for network and there is a manual custom :D

**Comment by StapleButter** [comment]
oh, that

it'll be automatic as well, but I'm not working on it for now

**Comment by Heoz** [comment]
Don't know if you will see this but tried Mario Kart with Threaded 3D but its only 45 fps and when you don't use Threaded 3D its still 45 fps but other games seem to get 20 30 fps boost with Threaded :D

**Comment by StapleButter** [comment]
please make a new issue instead of trying to reuse an existing issue that is completely different, that's confusing
