### ISSUE TITLE
Tom Clancy's Splinter Cell - Chaos Theory (USA) (En,Fr,De,Es,It) bugs

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#56]
start a new game then if you choose night vision or thermal vision the top screen glitches

**Comment by scottluker** [comment]
With thermal vision it seems to be flickering between two images, both screenshotted below.

![2017-06-14_09-42-57](https://user-images.githubusercontent.com/8451624/27123565-2fe119ec-50e6-11e7-9228-b4497b5b6503.png)
![2017-06-14_09-43-07](https://user-images.githubusercontent.com/8451624/27123566-300014fa-50e6-11e7-8ac6-12b4d3d96817.png)

**Comment by StapleButter** [comment]
hey, surprise, a game that uses the display FIFO

that doesn't tell me why it shits itself, though.

**Comment by StapleButter** [comment]
the game does fakecolor rendering to VRAM, then processes it to do the thermalcam effect and writes the processed image to RAM

the display FIFO is used to blend it with something else (likely the HUD thing)

I haven't understood it fully, but... may just be a timing problem, as display FIFO DMA is still instant

the rendering process seems to span a whopping 6 frames
