### ISSUE TITLE
Nanostray (USA) graphic problems

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#57]
on the menu screen the background graphics keep on flickering and during gameplay the background graphics are missing

**Comment by benderscruffy** [comment]
Nanostray 2 (USA) has the same problems aswell

**Comment by scottluker** [comment]
The menu items and during gameplay is more like an clipping issue than flickering. Like it's something to do with depth.

**Comment by windwakr** [comment]
Nanostray's graphics aren't showing up properly because of failed box tests.

**Comment by StapleButter** [comment]
Boxtest issues again, heh. I don't know what's wrong with the boxtest code, I checked it again and it seems right.

But whatever, I'll keep trying.
