### ISSUE TITLE
Spectrobes (Europe) (En,Fr,De,Es,It) corrupt save

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#59]
every time you start the game it says the save is corrupt and you have to delete it

**Comment by StapleButter** [comment]
this game does shitty crap and may need a proper database.

**Comment by benderscruffy** [comment]
fixed

**Comment by benderscruffy** [comment]
sorry not fixed my mistake

**Comment by StapleButter** [comment]
fixed. save file should be 64K, delete it if it's not the case.
