### ISSUE TITLE
games with save issues

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#60]
Picross DS (Europe) (En,Fr,De,Es,It)
comes up with a save error 
![1](https://user-images.githubusercontent.com/2696404/27018551-140b9d10-4f64-11e7-8fd6-2d58f1a071ce.PNG)

**Comment by benderscruffy** [comment]
Chronicles of Narnia, The - The Lion, the Witch and the Wardrobe (USA) (En,Fr,Es,It,Nl) has the same problem
![2](https://user-images.githubusercontent.com/2696404/27019546-0c758ee6-4f6c-11e7-9291-2351cd9dc255.PNG)

**Comment by benderscruffy** [comment]
Jam with the Band (Europe) (En,Fr,De,Es,It) has the same problem
![3](https://user-images.githubusercontent.com/2696404/27073275-dd28210e-5055-11e7-8c71-087f52236481.PNG)

**Comment by benderscruffy** [comment]
Bee Game, The (USA) same problem
![4](https://user-images.githubusercontent.com/2696404/27081230-fe4ef6ca-5071-11e7-833d-5ac2476df2d8.PNG)

**Comment by benderscruffy** [comment]
Powerbike (USA)
![5](https://user-images.githubusercontent.com/2696404/27081535-7271b92e-5073-11e7-9ddf-c272ac6ff3e9.PNG)

**Comment by StapleButter** [comment]
first two games are known to be fixed by the last commit.

**Comment by Hexagon12** [comment]
Pokemon Mystery Dungeon - Explorers of Time, Darkness and Sky fail to save ingame with "Save failed."

**Comment by benderscruffy** [comment]
most of them are fixed 
will open seperate issues
