### ISSUE TITLE
Legend of Spyro, The - The Eternal Night (USA) intro problem

### ISSUE THREAD

**Issue by benderscruffy** [StapleButter/melonDS#61]
start a new game and during the intro the top screen the graphics are missing or glitched

**Comment by scottluker** [comment]
![2017-06-14_09-30-37](https://user-images.githubusercontent.com/8451624/27123025-774c0e4c-50e4-11e7-806f-f3336ad52e8e.png)
![2017-06-14_09-30-58](https://user-images.githubusercontent.com/8451624/27123026-776906dc-50e4-11e7-9cec-ae2c32e0019c.png)
