### ISSUE TITLE
Big Brain Academy (USA) firmware boot issue

### ISSUE THREAD

**Issue by SilasLaspada** [StapleButter/melonDS#63]
When this game is run via firmware boot, only the bottom screen works. The top screen is completely white. This issue is not present when booting the game directly.

**Comment by StapleButter** [comment]
probably the game being lazy with its GPU init, like, just doing a power cycle and not clearing the registers

**Comment by SilasLaspada** [comment]
Appears to be fixed as of 51d29c8.
