### ISSUE TITLE
MelonDS with a hi-res 3D rendering

### ISSUE THREAD

**Issue by John-Enigma** [StapleButter/melonDS#7]
Is it possible for MelonDS top get a high-res 3D rendering option in the future, kinda like [DraStic's own high resolution rendering](http://www.neogaf.com/forum/showthread.php?t=798812)? 

I know what you're thinking: the images in here are subpar, considering that these images were posted a year ago. For all I know, this is still a WIP, but I'm pretty sure it has improved over time.

But again, is it still possible for you to make this option in the far future?

**Comment by John-Enigma** [comment]
^ Why not? I'm just suggesting.

**Comment by mudlord** [comment]
Why not? Because it adds complexity which shouldn't exist?

**Comment by StapleButter** [comment]
melonDS may eventually get hi-res rendering, but that will depend on whether it can be integrated into the codebase without adding too much complexity/slowdown. it's not high on the priority list at all.

mudlord, you aren't my spokesperson, thank you.

**Comment by John-Enigma** [comment]
^Thanks for the reply.
