### ISSUE TITLE
After changing name in ds settings and restarting, none of it saves, goes back to original

### ISSUE THREAD

**Issue by lordofharry** [StapleButter/melonDS#76]
After changing name in ds settings and restarting, none of it saves, goes back to original.

**Comment by lordofharry** [comment]
actually found it is saying it can not find the arm7 or arm9 file

**Comment by lordofharry** [comment]
Solved, found that the arm7 and 9 files needed to have their extension changed to .bin instead of .rom

**Comment by lordofharry** [comment]
Or just upload this version 4 compiled.

**Comment by lordofharry** [comment]
Solved, see http://melonds.kuribo64.net/board/thread.php?id=12

**Comment by Nadia-h** [comment]
You should probably create different issues for the problems you're having rather than reusing the same issue.

**Comment by mariogamer2** [comment]
Same thing for language and other settings...

**Comment by StapleButter** [comment]
done
