### ISSUE TITLE
Ace Attorney issues in older versions of DeSmuME

### ISSUE THREAD

**Issue by cghndmr** [StapleButter/melonDS#77]
In other than the latest version of DesMuME, the touch screen inspection thingy doesn't work.
 If I'm not wrong, it may need some fixing. [https://forums.desmume.org/viewtopic.php?id=191](url)

**Comment by Hexagon12** [comment]
Umm, I think you posted this issue in the wrong place. This is the melonDS emulator, but you are talking about DesMuME problems.
