### ISSUE TITLE
Sims 2 DS - broken music

### ISSUE THREAD

**Issue by Simonx22** [StapleButter/melonDS#78]
The sound effects in this game work fine but the music is really broken. This music doesn't sound that healthy. The title screen music works just fine tho.

Tested with melonDS 0.3 but this issue is maybe gone now... I'll try to compile the latest nightly and will see. (or i'll just wait for 0.4 if I fail to compile it)

**Comment by StapleButter** [comment]
seems linked to #79 in that the game seems to be loading bogus data from the ROM

**Comment by StapleButter** [comment]
the game seems to run its own mixer (on the ARM9, way to go), and that's not working right

maybe a timing problem.

the intro is unaffected because its audio playback bypasses the aforementioned mixer (even though it's still running at that time)
