### ISSUE TITLE
Sims 2 DS - door disappears

### ISSUE THREAD

**Issue by Simonx22** [StapleButter/melonDS#79]
When I'm to far away, the door disappears.
![image](https://user-images.githubusercontent.com/26326692/27384813-996248be-5690-11e7-8573-c5cc18a9f925.png)

But when I come closer, the door appears again.
![image](https://user-images.githubusercontent.com/26326692/27384829-a20a7fc2-5690-11e7-81fc-17c8a8cb3edb.png)

Tested with melonDS 0.3.

**Comment by StapleButter** [comment]
well, ad58a68fc979524d17858428ea8f755df3d212a5 seems to fix this
