### ISSUE TITLE
Lego Star Wars: The Complete Saga (USA) intro graphics glitch

### ISSUE THREAD

**Issue by SilasLaspada** [StapleButter/melonDS#80]
The text in the intro of this game is garbled. This issue was not present in earlier versions of MelonDS, and it appears that the "guilty" commit is 568b9fbf49beda49b43b52f6af12d821835b766f 

![ndsstar](https://user-images.githubusercontent.com/24215969/27503907-c6de7a6a-583e-11e7-99a6-c5466d33101a.PNG)

**Comment by SilasLaspada** [comment]
The text is displayed as it should be while fading in or out.

**Comment by StapleButter** [comment]
the game enables antialiasing and, for some reason, edge marking, even though it's not applied to anything here

but the problem is polygons leaking over eachother. this will require implementing antialiasing.

**Comment by StapleButter** [comment]
actually it didn't require antialiasing
