### ISSUE TITLE
After saving settings, emulator will not run again unless closed

### ISSUE THREAD

**Issue by obso1337** [StapleButter/melonDS#83]
After your most recent save functionality you added, after saving user settings and choosing shutdown in the ds, you can not choose run again as it freezes or does not respond.

**Comment by StapleButter** [comment]
'Run' only runs the firmware if nothing else has been loaded.

I could make it so that shutdown reverts melonDS to its initial state, so you can go and load something again.

**Comment by lordofharry** [comment]
Yeah that would work well.

**Comment by lordofharry** [comment]
Also since you are here, would you ever consider making a standalone pictochat client, it is so far the main reason i take interest in this emulator, it could become an actually cool messaging program especially if it could be made to run off a server instead of p2p.

**Comment by Nadia-h** [comment]
If you wanted something like that, you'd probably be better off just writing your own Pictochat clone from scratch.

**Comment by lordofharry** [comment]
Yeah that is what i was thinking.

**Comment by StapleButter** [comment]
should be fixed since then, those commands seem quite robust these days

let me know if not.
