### ISSUE TITLE
Super Mario 64 DS: Flickering ground texture in Cool Cool Mountain

### ISSUE THREAD

**Issue by Nadia-h** [StapleButter/melonDS#86]
In Super Mario 64 DS, this particular part of the ground in Cool Cool Mountain seems to flicker when viewing it from different angles or sometimes when standing still.

![Image](https://user-images.githubusercontent.com/893884/27662468-28ccd9a6-5c5e-11e7-85dc-f19c0ff2997e.png)

**Comment by JMC47** [comment]
Can confirm, tried this out myself.

**Comment by StapleButter** [comment]
it doesn't flicker if I disable culling (but some other bits still flicker..?)
