### ISSUE TITLE
Metroid Prime Hunters - Graphical issues

### ISSUE THREAD

**Issue by kabili207** [StapleButter/melonDS#88]
![screenshot_2017-07-01_14-37-45](https://user-images.githubusercontent.com/1270500/27764603-3089f674-5e6b-11e7-996b-83748ebf76e5.png)

**Comment by StapleButter** [comment]
that's... interesting, to say the least

where does it happen specifically in the game?

**Comment by kabili207** [comment]
Sorry, I forgot metion that. This is the menu thats immediately after intro video that plays when you boot the game up. Three screenshot shows it trying to render the "Press Start" screen.

**Comment by StapleButter** [comment]
which ROM version?

I tried the U version and it renders fine

**Comment by kabili207** [comment]
I compiled the latest revision and it seems to be working fine now. I guess I was running an older version than I thought I was.
