### ISSUE TITLE
Etrian Odyssey - Warps do not completely white out screen

### ISSUE THREAD

**Issue by JMC47** [StapleButter/melonDS#93]
There's a slight issue with fades where part of the screen doesn't fade out.  Looks like a depth issue.

![eomelondsfade](https://user-images.githubusercontent.com/6598209/28197707-a4ac8a3e-6826-11e7-80a0-1b7a9fe0d5e1.png)

Verified on hardware that this does not happen.

**Comment by StapleButter** [comment]
this was said to be fixed on the latest revision, so
