### ISSUE TITLE
melonDS can't be shut down from inside the firmware

### ISSUE THREAD

**Issue by ehea617** [StapleButter/melonDS#94]
Any dialog in the firmware that is supposed to shut down a physical DS does not shut down melonDS. When inside pictochat and choosing quit, the yes button does not quit melonDS. In fact, it doesn't seem to do anything. When attempting to quit from the settings or DS Download Play, the screen will fade to black and melonDS will still be running.

**Comment by StapleButter** [comment]
if I were to implement that, I'd rather have it reset melonDS to its initial "no ROM loaded" state, than outright closing it.

**Comment by ehea617** [comment]
That's what I was thinking, I just worded it badly.

**Comment by Nadia-h** [comment]
This was implemented in https://github.com/StapleButter/melonDS/commit/495d0ba12d140fc205fbfbe491b6ddd8d6dbe891
