### ISSUE TITLE
Pirates of the Carribean - At World's End (US) black screen

### ISSUE THREAD

**Issue by angrylion7** [StapleButter/melonDS#97]
This game seems to not render any graphics with melonDS 0.4, with any settings, booting directly or from firmware. The music plays OK, and it seems that the game's initial menus can be navigated by blind mouse clicks or button presses. In the melonDS console the following is printed before the first invisible screen (which is a language select screen):

FW: WIFI CRC16 = GOOD
FW: AP1 CRC16 = GOOD
FW: AP2 CRC16 = GOOD
FW: AP3 CRC16 = GOOD
FW: USER0 CRC16 = GOOD
FW: USER1 CRC16 = GOOD
ARM9: offset=00004000 entry=02000800 RAM=02000000 size=000AC904
ARM7: offset=000B0A00 entry=02380000 RAM=02380000 size=000286B0
Re-encrypting cart secure area
Save file: my save file path
unknown CP15 write op 600 04000033
unknown CP15 write op 610 0200002D
unknown CP15 write op 620 027E0021
unknown CP15 write op 630 08000035
unknown CP15 write op 640 027E001B
unknown CP15 write op 650 0100002F
unknown CP15 write op 660 FFFF001D
unknown CP15 write op 670 027FF017
unknown CP15 write op 201 00000042
unknown CP15 write op 200 00000042
unknown CP15 write op 300 00000002
unknown CP15 write op 503 05100011
unknown CP15 write op 502 15111011
unknown CP15 write op 610 0200002B
unknown CP15 write op 620 023E0021
unknown arm7 read16 08000004 03807250
unknown CP15 read op 502
unknown CP15 write op 502 00005000
unknown ARM7 IO write16 04000206 0030
unknown ARM9 IO write32 04001060 00000000
unknown ARM9 IO write32 04001064 00000000
unknown ARM9 IO write32 04001068 00000000
unknown ARM9 IO write32 0400106C 00000000
unknown save SPI command 01 F0
unknown ARM9 IO write32 0400006C 00008010

**Comment by StapleButter** [comment]
was fixed, probably by e6f5507c9e73ee2bdb7089cb9588c769c170b57c
