### ISSUE TITLE
Broken graphics in some Download Play demos

### ISSUE THREAD

**Issue by mariomadproductions** [StapleButter/melonDS#98]
There are broken graphics in the following Download Play demo ROMs at least:

**Key**
_Name_
desmume screenshot/melonds screenshot

**Screenshots**
_Mario vs. Donkey Kong 2 - March of the Minis (USA) (Demo) (Kiosk,Multiboot,Download Station Vol. 3)_
![mario vs donkey kong 2 - march of the minis usa demo kiosk multiboot download station vol 3 __15793](https://user-images.githubusercontent.com/9919020/28317970-ebdec938-6bc0-11e7-9fb6-eec0d6a0fc8d.png)![2017-07-18 13_57_13-paused - melonds 0 4](https://user-images.githubusercontent.com/9919020/28318004-0f0a6138-6bc1-11e7-83db-6531b5e3e8de.png)

_Mario vs. Donkey Kong 2 - March of the Minis (Europe) (Demo) (Kiosk,Multiboot,Download Station Vol. 3)_
![mario vs donkey kong 2 - march of the minis europe demo kiosk multiboot download station vol 3 __15297](https://user-images.githubusercontent.com/9919020/28317870-8ff0c446-6bc0-11e7-8d09-32444de0b90b.png)![2017-07-18 13_55_19-2017_07_18_13_55_07_nintendo_nintendo_ds_download_play_beta_ png - paint net 4 0](https://user-images.githubusercontent.com/9919020/28317944-cdc3fafe-6bc0-11e7-9c60-51555132fded.png)

**Comment by XXLuigiMario** [comment]
This is not specifically linked to Download Play demos, but to Mario vs. Donkey Kong 2 in particular.
These issues are present all throughout the game.

![brokengraphics1](https://user-images.githubusercontent.com/7153662/28329462-32251784-6bea-11e7-9ab4-b9d3681d9540.png) ![brokengraphics3](https://user-images.githubusercontent.com/7153662/28329461-32099aea-6bea-11e7-8012-878161919774.png) ![brokengraphics2](https://user-images.githubusercontent.com/7153662/28329463-3225a302-6bea-11e7-83fd-b01fc81e9754.png) ![brokengraphics4](https://user-images.githubusercontent.com/7153662/28329544-7d5f2e6a-6bea-11e7-8dc7-ca365c70bd25.png)

**Comment by mariomadproductions** [comment]
Seems like Desmume sometimes does a similar thing to this with the normal USA version.

**Comment by StapleButter** [comment]
iirc the layer switches in desmume are XOR, ie. disabling a layer that the game has disabled will actually enable it

but I'd have to check their code again
